export const NBA_CONFERENCES: {
  name: string;
  divisions: { name: string; teams: string[] }[];
}[] = [
  {
    name: "Eastern Conference",
    divisions: [
      { name: "Atlantic",  teams: ["Boston Celtics","Brooklyn Nets","New York Knicks","Philadelphia 76ers","Toronto Raptors"] },
      { name: "Central",   teams: ["Chicago Bulls","Cleveland Cavaliers","Detroit Pistons","Indiana Pacers","Milwaukee Bucks"] },
      { name: "Southeast", teams: ["Atlanta Hawks","Charlotte Hornets","Miami Heat","Orlando Magic","Washington Wizards"] },
    ],
  },
  {
    name: "Western Conference",
    divisions: [
      { name: "Northwest", teams: ["Denver Nuggets","Minnesota Timberwolves","Oklahoma City Thunder","Portland Trail Blazers","Utah Jazz"] },
      { name: "Pacific",   teams: ["Golden State Warriors","LA Clippers","Los Angeles Lakers","Phoenix Suns","Sacramento Kings"] },
      { name: "Southwest", teams: ["Dallas Mavericks","Houston Rockets","Memphis Grizzlies","New Orleans Pelicans","San Antonio Spurs"] },
    ],
  },
];

export const NBA_TEAMS: { name: string; aliases: string[] }[] = [
  { name: "Atlanta Hawks",          aliases: ["hawks","atlanta","atl"] },
  { name: "Boston Celtics",         aliases: ["celtics","boston","bos"] },
  { name: "Brooklyn Nets",          aliases: ["nets","brooklyn","bkn","bk nets"] },
  { name: "Charlotte Hornets",      aliases: ["hornets","charlotte","cha"] },
  { name: "Chicago Bulls",          aliases: ["bulls","chicago","chi"] },
  { name: "Cleveland Cavaliers",    aliases: ["cavaliers","cavs","cleveland","cle"] },
  { name: "Dallas Mavericks",       aliases: ["mavericks","mavs","dallas","dal"] },
  { name: "Denver Nuggets",         aliases: ["nuggets","denver","den"] },
  { name: "Detroit Pistons",        aliases: ["pistons","detroit","det"] },
  { name: "Golden State Warriors",  aliases: ["warriors","golden state","gsw","golden state warriors"] },
  { name: "Houston Rockets",        aliases: ["rockets","houston","hou"] },
  { name: "Indiana Pacers",         aliases: ["pacers","indiana","ind"] },
  { name: "LA Clippers",            aliases: ["clippers","la clippers","lac","los angeles clippers"] },
  { name: "Los Angeles Lakers",     aliases: ["lakers","la lakers","lal","los angeles lakers"] },
  { name: "Memphis Grizzlies",      aliases: ["grizzlies","memphis","mem"] },
  { name: "Miami Heat",             aliases: ["heat","miami","mia"] },
  { name: "Milwaukee Bucks",        aliases: ["bucks","milwaukee","mil"] },
  { name: "Minnesota Timberwolves", aliases: ["timberwolves","wolves","minnesota","min","twolves"] },
  { name: "New Orleans Pelicans",   aliases: ["pelicans","new orleans","nop","no pelicans"] },
  { name: "New York Knicks",        aliases: ["knicks","new york","nyk","ny knicks"] },
  { name: "Oklahoma City Thunder",  aliases: ["thunder","oklahoma city","okc","oklahoma"] },
  { name: "Orlando Magic",          aliases: ["magic","orlando","orl"] },
  { name: "Philadelphia 76ers",     aliases: ["76ers","sixers","philadelphia","phi","philly","76 ers"] },
  { name: "Phoenix Suns",           aliases: ["suns","phoenix","phx"] },
  { name: "Portland Trail Blazers", aliases: ["trail blazers","blazers","portland","por"] },
  { name: "Sacramento Kings",       aliases: ["kings","sacramento","sac"] },
  { name: "San Antonio Spurs",      aliases: ["spurs","san antonio","sas"] },
  { name: "Toronto Raptors",        aliases: ["raptors","toronto","tor"] },
  { name: "Utah Jazz",              aliases: ["jazz","utah","uta"] },
  { name: "Washington Wizards",     aliases: ["wizards","washington","was","wsh"] },
];

// 6 players per team: PG, SG, SF, PF, C, + 1 bench (2025-26 playoffs depth chart)
export const TEAM_ROSTERS: Record<string, string[]> = {
  "Atlanta Hawks":           ["CJ McCollum", "Nickeil Alexander-Walker", "Dyson Daniels", "Jalen Johnson", "Onyeka Okongwu", "De'Andre Hunter"],
  "Boston Celtics":          ["Derrick White", "Jaylen Brown", "Sam Hauser", "Jayson Tatum", "Neemias Queta", "Payton Pritchard"],
  "Brooklyn Nets":           ["Egor Demin", "Dwight Powell", "Michael Porter Jr.", "Noah Clowney", "Nic Claxton", "Cam Thomas"],
  "Charlotte Hornets":       ["LaMelo Ball", "Kon Knueppel", "Brandon Miller", "Miles Bridges", "Moussa Diabate", "Nick Richards"],
  "Chicago Bulls":           ["Josh Giddey", "Tre Jones", "Isaac Okoro", "Matas Buzelis", "Jalen Smith", "Patrick Williams"],
  "Cleveland Cavaliers":     ["James Harden", "Donovan Mitchell", "Dean Wade", "Evan Mobley", "Jarrett Allen", "Max Strus"],
  "Dallas Mavericks":        ["Kyrie Irving", "Max Christie", "Cooper Flagg", "PJ Washington", "Dereck Lively II", "Daniel Gafford"],
  "Denver Nuggets":          ["Jamal Murray", "Christian Braun", "Cameron Johnson", "Aaron Gordon", "Nikola Jokic", "Peyton Watson"],
  "Detroit Pistons":         ["Cade Cunningham", "Duncan Robinson", "Ausar Thompson", "Tobias Harris", "Jalen Duren", "Isaiah Stewart"],
  "Golden State Warriors":   ["Stephen Curry", "Brandin Podziemski", "Gui Santos", "Draymond Green", "Kristaps Porzingis", "Moses Moody"],
  "Houston Rockets":         ["Fred VanVleet", "Amen Thompson", "Kevin Durant", "Jabari Smith Jr.", "Alperen Sengun", "Tari Eason"],
  "Indiana Pacers":          ["Tyrese Haliburton", "Andrew Nembhard", "Aaron Nesmith", "Pascal Siakam", "Ivica Zubac", "Bennedict Mathurin"],
  "LA Clippers":             ["Darius Garland", "Kris Dunn", "Kawhi Leonard", "Derrick Jones Jr.", "Brook Lopez", "Terance Mann"],
  "Los Angeles Lakers":      ["Luka Doncic", "Austin Reaves", "Marcus Smart", "LeBron James", "Deandre Ayton", "Rui Hachimura"],
  "Memphis Grizzlies":       ["Ja Morant", "Cam Coward", "Jaylen Wells", "Santi Aldama", "Zach Edey", "Luke Kennard"],
  "Miami Heat":              ["Davion Mitchell", "Tyler Herro", "Norman Powell", "Andrew Wiggins", "Bam Adebayo", "Nikola Jovic"],
  "Milwaukee Bucks":         ["Ryan Rollins", "Kevin Porter Jr.", "Kyle Kuzma", "Giannis Antetokounmpo", "Myles Turner", "Pat Connaughton"],
  "Minnesota Timberwolves":  ["Ayo Dosunmu", "Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert", "Naz Reid"],
  "New Orleans Pelicans":    ["Dejounte Murray", "Trey Murphy III", "Saddiq Bey", "Zion Williamson", "Herb Jones", "Jose Alvarado"],
  "New York Knicks":         ["Jalen Brunson", "Josh Hart", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns", "Mitchell Robinson"],
  "Oklahoma City Thunder":   ["Shai Gilgeous-Alexander", "Luguentz Dort", "Jalen Williams", "Chet Holmgren", "Isaiah Hartenstein", "Aaron Wiggins"],
  "Orlando Magic":           ["Jalen Suggs", "Desmond Bane", "Franz Wagner", "Paolo Banchero", "Wendell Carter Jr.", "Moritz Wagner"],
  "Philadelphia 76ers":      ["Tyrese Maxey", "VJ Edgecombe", "Kelly Oubre Jr.", "Paul George", "Joel Embiid", "Andre Drummond"],
  "Phoenix Suns":            ["Devin Booker", "Jalen Green", "Jordan Goodwin", "Dillon Brooks", "Mark Williams", "Royce O'Neale"],
  "Portland Trail Blazers":  ["Scoot Henderson", "Jrue Holiday", "Toumani Camara", "Deni Avdija", "Donovan Clingan", "Anfernee Simons"],
  "Sacramento Kings":        ["Russell Westbrook", "Zach LaVine", "DeMar DeRozan", "Keegan Murray", "Domantas Sabonis", "Harrison Barnes"],
  "San Antonio Spurs":       ["De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Julian Champagnie", "Victor Wembanyama", "Keldon Johnson"],
  "Toronto Raptors":         ["Immanuel Quickley", "Brandon Ingram", "RJ Barrett", "Scottie Barnes", "Jakob Poeltl", "Gradey Dick"],
  "Utah Jazz":               ["Keyonte George", "Ace Bailey", "Lauri Markkanen", "Jaren Jackson Jr.", "Walker Kessler", "John Collins"],
  "Washington Wizards":      ["Trae Young", "Kyshawn George", "Bilal Coulibaly", "Anthony Davis", "Alexandre Sarr", "Jordan Poole"],
};
