export const NBA_CONFERENCES: {
  name: string;
  divisions: { name: string; teams: string[] }[];
}[] = [
  {
    name: "Eastern Conference",
    divisions: [
      { name: "Atlantic",  teams: ["Boston Celtics","Brooklyn Nets","New York Knicks","Philadelphia 76ers","Toronto Raptors"] },
      { name: "Central",   teams: ["Chicago Bulls","Cleveland Cavaliers","Detroit Pistons","Indiana Pacers","Milwaukee Bucks"] },
      { name: "Southeast", teams: ["Atlanta Hawks","Charlotte Hornets","Miami Heat","Orlando Magic","Washington Wizards"] },
    ],
  },
  {
    name: "Western Conference",
    divisions: [
      { name: "Northwest", teams: ["Denver Nuggets","Minnesota Timberwolves","Oklahoma City Thunder","Portland Trail Blazers","Utah Jazz"] },
      { name: "Pacific",   teams: ["Golden State Warriors","LA Clippers","Los Angeles Lakers","Phoenix Suns","Sacramento Kings"] },
      { name: "Southwest", teams: ["Dallas Mavericks","Houston Rockets","Memphis Grizzlies","New Orleans Pelicans","San Antonio Spurs"] },
    ],
  },
];

export const NBA_TEAMS: { name: string; aliases: string[] }[] = [
  { name: "Atlanta Hawks",          aliases: ["hawks","atlanta","atl"] },
  { name: "Boston Celtics",         aliases: ["celtics","boston","bos"] },
  { name: "Brooklyn Nets",          aliases: ["nets","brooklyn","bkn","bk nets"] },
  { name: "Charlotte Hornets",      aliases: ["hornets","charlotte","cha"] },
  { name: "Chicago Bulls",          aliases: ["bulls","chicago","chi"] },
  { name: "Cleveland Cavaliers",    aliases: ["cavaliers","cavs","cleveland","cle"] },
  { name: "Dallas Mavericks",       aliases: ["mavericks","mavs","dallas","dal"] },
  { name: "Denver Nuggets",         aliases: ["nuggets","denver","den"] },
  { name: "Detroit Pistons",        aliases: ["pistons","detroit","det"] },
  { name: "Golden State Warriors",  aliases: ["warriors","golden state","gsw","golden state warriors"] },
  { name: "Houston Rockets",        aliases: ["rockets","houston","hou"] },
  { name: "Indiana Pacers",         aliases: ["pacers","indiana","ind"] },
  { name: "LA Clippers",            aliases: ["clippers","la clippers","lac","los angeles clippers"] },
  { name: "Los Angeles Lakers",     aliases: ["lakers","la lakers","lal","los angeles lakers"] },
  { name: "Memphis Grizzlies",      aliases: ["grizzlies","memphis","mem"] },
  { name: "Miami Heat",             aliases: ["heat","miami","mia"] },
  { name: "Milwaukee Bucks",        aliases: ["bucks","milwaukee","mil"] },
  { name: "Minnesota Timberwolves", aliases: ["timberwolves","wolves","minnesota","min","twolves"] },
  { name: "New Orleans Pelicans",   aliases: ["pelicans","new orleans","nop","no pelicans"] },
  { name: "New York Knicks",        aliases: ["knicks","new york","nyk","ny knicks"] },
  { name: "Oklahoma City Thunder",  aliases: ["thunder","oklahoma city","okc","oklahoma"] },
  { name: "Orlando Magic",          aliases: ["magic","orlando","orl"] },
  { name: "Philadelphia 76ers",     aliases: ["76ers","sixers","philadelphia","phi","philly","76 ers"] },
  { name: "Phoenix Suns",           aliases: ["suns","phoenix","phx"] },
  { name: "Portland Trail Blazers", aliases: ["trail blazers","blazers","portland","por"] },
  { name: "Sacramento Kings",       aliases: ["kings","sacramento","sac"] },
  { name: "San Antonio Spurs",      aliases: ["spurs","san antonio","sas"] },
  { name: "Toronto Raptors",        aliases: ["raptors","toronto","tor"] },
  { name: "Utah Jazz",              aliases: ["jazz","utah","uta"] },
  { name: "Washington Wizards",     aliases: ["wizards","washington","was","wsh"] },
];

// 6 players per team: PG, SG, SF, PF, C, + 1 bench (2025-26 starters)
export const TEAM_ROSTERS: Record<string, string[]> = {
  "Atlanta Hawks":          ["Dyson Daniels", "Bogdan Bogdanovic", "De'Andre Hunter", "Jalen Johnson", "Clint Capela", "Onyeka Okongwu"],
  "Boston Celtics":         ["Jrue Holiday", "Jaylen Brown", "Jayson Tatum", "Al Horford", "Kristaps Porzingis", "Payton Pritchard"],
  "Brooklyn Nets":          ["Cam Thomas", "Keon Johnson", "Ziaire Williams", "Noah Clowney", "Nic Claxton", "Day'Ron Sharpe"],
  "Charlotte Hornets":      ["LaMelo Ball", "Brandon Miller", "Miles Bridges", "Grant Williams", "Mark Williams", "Nick Richards"],
  "Chicago Bulls":          ["Coby White", "Josh Giddey", "Patrick Williams", "Torrey Craig", "Nikola Vucevic", "Ayo Dosunmu"],
  "Cleveland Cavaliers":    ["James Harden", "Donovan Mitchell", "Isaac Okoro", "Evan Mobley", "Jarrett Allen", "Ty Jerome"],
  "Dallas Mavericks":       ["Kyrie Irving", "Klay Thompson", "Cooper Flagg", "PJ Washington", "Daniel Gafford", "Jaden Hardy"],
  "Denver Nuggets":         ["Jamal Murray", "Kentavious Caldwell-Pope", "Michael Porter Jr.", "Aaron Gordon", "Nikola Jokic", "Christian Braun"],
  "Detroit Pistons":        ["Cade Cunningham", "Jaden Ivey", "Ausar Thompson", "Isaiah Stewart", "Jalen Duren", "Simone Fontecchio"],
  "Golden State Warriors":  ["Stephen Curry", "Buddy Hield", "Andrew Wiggins", "Draymond Green", "Kevon Looney", "Moses Moody"],
  "Houston Rockets":        ["Fred VanVleet", "Jalen Green", "Kevin Durant", "Jabari Smith Jr.", "Alperen Sengun", "Dillon Brooks"],
  "Indiana Pacers":         ["Tyrese Haliburton", "Andrew Nembhard", "Aaron Nesmith", "Pascal Siakam", "Myles Turner", "Bennedict Mathurin"],
  "LA Clippers":            ["Darius Garland", "Norman Powell", "Kawhi Leonard", "Nicolas Batum", "Ivica Zubac", "Bones Hyland"],
  "Los Angeles Lakers":     ["Luka Doncic", "Austin Reaves", "LeBron James", "Rui Hachimura", "Jaxson Hayes", "Gabe Vincent"],
  "Memphis Grizzlies":      ["Ja Morant", "Desmond Bane", "GG Jackson", "Santi Aldama", "Zach Edey", "Luke Kennard"],
  "Miami Heat":             ["Terry Rozier", "Tyler Herro", "Jimmy Butler", "Caleb Martin", "Bam Adebayo", "Duncan Robinson"],
  "Milwaukee Bucks":        ["Malik Beasley", "Khris Middleton", "MarJon Beauchamp", "Giannis Antetokounmpo", "Brook Lopez", "Bobby Portis"],
  "Minnesota Timberwolves": ["Mike Conley", "Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert", "Naz Reid"],
  "New Orleans Pelicans":   ["CJ McCollum", "Herb Jones", "Zion Williamson", "Larry Nance Jr.", "Jonas Valanciunas", "Trey Murphy III"],
  "New York Knicks":        ["Jalen Brunson", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns", "Mitchell Robinson", "Josh Hart"],
  "Oklahoma City Thunder":  ["Shai Gilgeous-Alexander", "Luguentz Dort", "Jalen Williams", "Chet Holmgren", "Isaiah Hartenstein", "Aaron Wiggins"],
  "Orlando Magic":          ["Jalen Suggs", "Cole Anthony", "Franz Wagner", "Paolo Banchero", "Wendell Carter Jr.", "Jonathan Isaac"],
  "Philadelphia 76ers":     ["Tyrese Maxey", "Paul George", "Kelly Oubre Jr.", "Tobias Harris", "Joel Embiid", "Andre Drummond"],
  "Phoenix Suns":           ["Bradley Beal", "Devin Booker", "Royce O'Neale", "Eric Gordon", "Jusuf Nurkic", "Grayson Allen"],
  "Portland Trail Blazers": ["Damian Lillard", "Anfernee Simons", "Matisse Thybulle", "Jerami Grant", "Deandre Ayton", "Shaedon Sharpe"],
  "Sacramento Kings":       ["Keyonte George", "Zach LaVine", "Harrison Barnes", "Kevin Huerter", "Domantas Sabonis", "Malik Monk"],
  "San Antonio Spurs":      ["De'Aaron Fox", "Devin Vassell", "Keldon Johnson", "Jeremy Sochan", "Victor Wembanyama", "Zach Collins"],
  "Toronto Raptors":        ["Immanuel Quickley", "Brandon Ingram", "Scottie Barnes", "Kelly Olynyk", "Jakob Poeltl", "Gradey Dick"],
  "Utah Jazz":              ["Collin Sexton", "Jordan Clarkson", "Lauri Markkanen", "Jaren Jackson Jr.", "Walker Kessler", "John Collins"],
  "Washington Wizards":     ["Trae Young", "Jordan Poole", "Kyle Kuzma", "Anthony Davis", "Alexandre Sarr", "Corey Kispert"],
};
