export const NBA_TEAMS: { name: string; aliases: string[] }[] = [
  { name: "Atlanta Hawks",          aliases: ["hawks","atlanta","atl"] },
  { name: "Boston Celtics",         aliases: ["celtics","boston","bos"] },
  { name: "Brooklyn Nets",          aliases: ["nets","brooklyn","bkn","bk nets"] },
  { name: "Charlotte Hornets",      aliases: ["hornets","charlotte","cha"] },
  { name: "Chicago Bulls",          aliases: ["bulls","chicago","chi"] },
  { name: "Cleveland Cavaliers",    aliases: ["cavaliers","cavs","cleveland","cle"] },
  { name: "Dallas Mavericks",       aliases: ["mavericks","mavs","dallas","dal"] },
  { name: "Denver Nuggets",         aliases: ["nuggets","denver","den"] },
  { name: "Detroit Pistons",        aliases: ["pistons","detroit","det"] },
  { name: "Golden State Warriors",  aliases: ["warriors","golden state","gsw","golden state warriors"] },
  { name: "Houston Rockets",        aliases: ["rockets","houston","hou"] },
  { name: "Indiana Pacers",         aliases: ["pacers","indiana","ind"] },
  { name: "LA Clippers",            aliases: ["clippers","la clippers","lac","los angeles clippers"] },
  { name: "Los Angeles Lakers",     aliases: ["lakers","la lakers","lal","los angeles lakers"] },
  { name: "Memphis Grizzlies",      aliases: ["grizzlies","memphis","mem"] },
  { name: "Miami Heat",             aliases: ["heat","miami","mia"] },
  { name: "Milwaukee Bucks",        aliases: ["bucks","milwaukee","mil"] },
  { name: "Minnesota Timberwolves", aliases: ["timberwolves","wolves","minnesota","min","twolves"] },
  { name: "New Orleans Pelicans",   aliases: ["pelicans","new orleans","nop","no pelicans"] },
  { name: "New York Knicks",        aliases: ["knicks","new york","nyk","ny knicks"] },
  { name: "Oklahoma City Thunder",  aliases: ["thunder","oklahoma city","okc","oklahoma"] },
  { name: "Orlando Magic",          aliases: ["magic","orlando","orl"] },
  { name: "Philadelphia 76ers",     aliases: ["76ers","sixers","philadelphia","phi","philly","76 ers"] },
  { name: "Phoenix Suns",           aliases: ["suns","phoenix","phx"] },
  { name: "Portland Trail Blazers", aliases: ["trail blazers","blazers","portland","por"] },
  { name: "Sacramento Kings",       aliases: ["kings","sacramento","sac"] },
  { name: "San Antonio Spurs",      aliases: ["spurs","san antonio","sas"] },
  { name: "Toronto Raptors",        aliases: ["raptors","toronto","tor"] },
  { name: "Utah Jazz",              aliases: ["jazz","utah","uta"] },
  { name: "Washington Wizards",     aliases: ["wizards","washington","was","wsh"] },
];

export const TEAM_ROSTERS: Record<string, string[]> = {
  "Atlanta Hawks": [
    "Trae Young","Dejounte Murray","Clint Capela","John Collins","De'Andre Hunter",
    "Bogdan Bogdanovic","Onyeka Okongwu","Jalen Johnson","Dominique Wilkins",
    "Dikembe Mutombo","Spud Webb","Lou Hudson","Bob Pettit","Steve Smith","Alan Henderson",
  ],
  "Boston Celtics": [
    "Jayson Tatum","Jaylen Brown","Al Horford","Marcus Smart","Robert Williams",
    "Kemba Walker","Paul Pierce","Kevin Garnett","Ray Allen","Isaiah Thomas",
    "Larry Bird","Bill Russell","Bob Cousy","John Havlicek","Kevin McHale","Dave Cowens",
  ],
  "Brooklyn Nets": [
    "Mikal Bridges","Ben Simmons","Kevin Durant","James Harden","Kyrie Irving",
    "Spencer Dinwiddie","Caris LeVert","Jarrett Allen","Brook Lopez",
    "Jason Kidd","Vince Carter","Richard Jefferson","Drazen Petrovic","Kenny Anderson","Stephon Marbury",
  ],
  "Charlotte Hornets": [
    "LaMelo Ball","Terry Rozier","Miles Bridges","Gordon Hayward","P.J. Washington",
    "Kemba Walker","Baron Davis","Alonzo Mourning","Larry Johnson","Glen Rice",
    "Muggsy Bogues","Dell Curry","Rex Chapman","Emeka Okafor","Gerald Wallace",
  ],
  "Chicago Bulls": [
    "DeMar DeRozan","Zach LaVine","Nikola Vucevic","Alex Caruso","Patrick Williams",
    "Michael Jordan","Scottie Pippen","Dennis Rodman","Horace Grant","Luol Deng",
    "Derrick Rose","Bob Love","Norm Van Lier","Artis Gilmore","Joakim Noah",
  ],
  "Cleveland Cavaliers": [
    "Donovan Mitchell","Darius Garland","Evan Mobley","Jarrett Allen","Caris LeVert",
    "LeBron James","Kyrie Irving","Kevin Love","Anderson Varejao","Zydrunas Ilgauskas",
    "Brad Daugherty","Mark Price","Larry Nance","World B. Free","Austin Carr",
  ],
  "Dallas Mavericks": [
    "Luka Doncic","Kyrie Irving","Tim Hardaway Jr.","Dorian Finney-Smith","Maxi Kleber",
    "Dirk Nowitzki","Steve Nash","Jason Kidd","Michael Finley","Shawn Marion",
    "Rolando Blackman","Derek Harper","Brad Davis","Brad Miller","Jamal Mashburn",
  ],
  "Denver Nuggets": [
    "Nikola Jokic","Jamal Murray","Michael Porter Jr.","Aaron Gordon","Kentavious Caldwell-Pope",
    "Carmelo Anthony","Alex English","Dan Issel","Dikembe Mutombo","Fat Lever",
    "David Thompson","Chauncey Billups","Reggie Jackson","Gary Harris","Will Barton",
  ],
  "Detroit Pistons": [
    "Cade Cunningham","Jalen Duren","Bojan Bogdanovic","Isaiah Stewart","Killian Hayes",
    "Ben Wallace","Chauncey Billups","Richard Hamilton","Rasheed Wallace","Joe Dumars",
    "Isiah Thomas","Bill Laimbeer","Dennis Rodman","Bob Lanier","Dave Bing",
  ],
  "Golden State Warriors": [
    "Stephen Curry","Klay Thompson","Draymond Green","Andrew Wiggins","Kevon Looney",
    "Kevin Durant","Andre Iguodala","Harrison Barnes","Shaun Livingston","Jordan Poole",
    "Chris Mullin","Mitch Richmond","Tim Hardaway","Rick Barry","Wilt Chamberlain",
  ],
  "Houston Rockets": [
    "Alperen Sengun","Jalen Green","Fred VanVleet","Jabari Smith Jr.","Kevin Porter Jr.",
    "James Harden","Russell Westbrook","Chris Paul","Dwight Howard","Yao Ming",
    "Tracy McGrady","Hakeem Olajuwon","Clyde Drexler","Calvin Murphy","Elvin Hayes",
  ],
  "Indiana Pacers": [
    "Tyrese Haliburton","Buddy Hield","Myles Turner","Bennedict Mathurin","Aaron Nesmith",
    "Reggie Miller","Jermaine O'Neal","Ron Artest","Rik Smits","Mark Jackson",
    "Chris Mullin","Detlef Schrempf","Dale Davis","Mel Daniels","Roger Brown",
  ],
  "LA Clippers": [
    "Kawhi Leonard","Paul George","James Harden","Ivica Zubac","Norman Powell",
    "Russell Westbrook","Marcus Morris","Patrick Beverley","Chris Paul","Blake Griffin",
    "DeAndre Jordan","Bob McAdoo","World B. Free","Norm Nixon","Randy Smith",
  ],
  "Los Angeles Lakers": [
    "LeBron James","Anthony Davis","Austin Reaves","D'Angelo Russell","Jarred Vanderbilt",
    "Kobe Bryant","Shaquille O'Neal","Magic Johnson","Kareem Abdul-Jabbar","Jerry West",
    "James Worthy","Pau Gasol","Elgin Baylor","Wilt Chamberlain","Nick Van Exel",
  ],
  "Memphis Grizzlies": [
    "Ja Morant","Desmond Bane","Jaren Jackson Jr.","Steven Adams","Dillon Brooks",
    "Mike Conley","Marc Gasol","Zach Randolph","Tony Allen","Rudy Gay",
    "Shane Battier","Pau Gasol","Stromile Swift","Lorenzen Wright","Mike Miller",
  ],
  "Miami Heat": [
    "Jimmy Butler","Bam Adebayo","Tyler Herro","Kyle Lowry","Max Strus",
    "LeBron James","Dwyane Wade","Shaquille O'Neal","Alonzo Mourning","Tim Hardaway",
    "Glen Rice","Chris Bosh","Ray Allen","Pat Riley","Udonis Haslem",
  ],
  "Milwaukee Bucks": [
    "Giannis Antetokounmpo","Khris Middleton","Jrue Holiday","Brook Lopez","Bobby Portis",
    "Kareem Abdul-Jabbar","Oscar Robertson","Bob Dandridge","Jon McGlocklin","Michael Redd",
    "Terry Cummings","Marques Johnson","Ray Allen","Bob Boozer","Jon McGlocklin",
  ],
  "Minnesota Timberwolves": [
    "Karl-Anthony Towns","Anthony Edwards","Rudy Gobert","Jaden McDaniels","Mike Conley",
    "D'Angelo Russell","Kevin Garnett","Stephon Marbury","Wally Szczerbiak","Sam Cassell",
    "Latrell Sprewell","Kevin Love","Andrew Wiggins","Ricky Rubio","Pooh Richardson",
  ],
  "New Orleans Pelicans": [
    "Zion Williamson","Brandon Ingram","C.J. McCollum","Jonas Valanciunas","Herbert Jones",
    "Trey Murphy III","Anthony Davis","Jrue Holiday","Chris Paul","Baron Davis",
    "David West","Peja Stojakovic","Tyson Chandler","Ryan Anderson","David Wesley",
  ],
  "New York Knicks": [
    "Jalen Brunson","Julius Randle","RJ Barrett","Mitchell Robinson","Josh Hart",
    "Immanuel Quickley","Patrick Ewing","Carmelo Anthony","Latrell Sprewell","Allan Houston",
    "Charles Oakley","Walt Frazier","Willis Reed","Dave DeBusschere","Earl Monroe",
  ],
  "Oklahoma City Thunder": [
    "Shai Gilgeous-Alexander","Chet Holmgren","Josh Giddey","Jalen Williams","Luguentz Dort",
    "Kevin Durant","Russell Westbrook","James Harden","Serge Ibaka","Paul George",
    "Nick Collison","Reggie Jackson","Gary Payton","Shawn Kemp","Detlef Schrempf",
  ],
  "Orlando Magic": [
    "Paolo Banchero","Franz Wagner","Wendell Carter Jr.","Jalen Suggs","Jonathan Isaac",
    "Shaquille O'Neal","Penny Hardaway","Dwight Howard","Tracy McGrady","Grant Hill",
    "Nick Anderson","Dennis Scott","Horace Grant","Patrick Ewing","Jameer Nelson",
  ],
  "Philadelphia 76ers": [
    "Joel Embiid","James Harden","Tyrese Maxey","Tobias Harris","Matisse Thybulle",
    "Allen Iverson","Charles Barkley","Julius Erving","Moses Malone","Wilt Chamberlain",
    "Billy Cunningham","Maurice Cheeks","Dolph Schayes","Hal Greer","Bobby Jones",
  ],
  "Phoenix Suns": [
    "Devin Booker","Kevin Durant","Bradley Beal","Jusuf Nurkic","Grayson Allen",
    "Chris Paul","Steve Nash","Charles Barkley","Kevin Johnson","Dan Majerle",
    "Shawn Marion","Amar'e Stoudemire","Jason Kidd","Connie Hawkins","Walter Davis",
  ],
  "Portland Trail Blazers": [
    "Damian Lillard","Anfernee Simons","Jerami Grant","Jusuf Nurkic","Robert Covington",
    "Gary Trent Jr.","Clyde Drexler","Bill Walton","Terry Porter","Buck Williams",
    "Arvydas Sabonis","Brandon Roy","LaMarcus Aldridge","Rasheed Wallace","Scottie Pippen",
  ],
  "Sacramento Kings": [
    "De'Aaron Fox","Domantas Sabonis","Malik Monk","Kevin Huerter","Harrison Barnes",
    "Keegan Murray","Mitch Richmond","Chris Webber","Vlade Divac","Jason Williams",
    "Peja Stojakovic","Brad Miller","Bobby Jackson","Pete Maravich","Nate Archibald",
  ],
  "San Antonio Spurs": [
    "Victor Wembanyama","Keldon Johnson","Tre Jones","Jeremy Sochan","Devin Vassell",
    "Tim Duncan","Tony Parker","Manu Ginobili","David Robinson","Sean Elliott",
    "George Gervin","Avery Johnson","Kawhi Leonard","LaMarcus Aldridge","Gregg Popovich",
  ],
  "Toronto Raptors": [
    "Scottie Barnes","OG Anunoby","Pascal Siakam","Fred VanVleet","Precious Achiuwa",
    "Kawhi Leonard","Kyle Lowry","DeMar DeRozan","Vince Carter","Tracy McGrady",
    "Chris Bosh","Damon Stoudamire","Antonio Davis","Muggsy Bogues","Andrea Bargnani",
  ],
  "Utah Jazz": [
    "Lauri Markkanen","Collin Sexton","Jordan Clarkson","Kelly Olynyk","John Collins",
    "Karl Malone","John Stockton","Mark Eaton","Deron Williams","Carlos Boozer",
    "Andrei Kirilenko","Mehmet Okur","Ricky Rubio","Pete Maravich","Adrian Dantley",
  ],
  "Washington Wizards": [
    "Bradley Beal","Jordan Poole","Kyle Kuzma","Daniel Gafford","Corey Kispert",
    "Kristaps Porzingis","Gilbert Arenas","John Wall","Elvin Hayes","Wes Unseld",
    "Walt Bellamy","Bob Dandridge","Antawn Jamison","Caron Butler","Mitch Richmond",
  ],
};
