import type { GuessWhoPlayer } from "./guessWhoData";

export const CURRENT_GUESS_WHO_PLAYERS: GuessWhoPlayer[] = [
  {
    id: "jokic_c",
    name: "Nikola Jokic",
    aliases: ["nikola jokic", "jokic", "the joker", "nikola"],
    teamColor: "#FEC524",
    team: "Denver Nuggets",
    position: "C",
    jersey: "15",
    clues: [
      "A center from Serbia who was selected 41st overall in the 2014 draft — widely considered the greatest draft steal ever.",
      "Has won the MVP award 3 times, more than any other active player.",
      "Led his team to their first-ever NBA championship in 2023, winning Finals MVP.",
      "Averages over 9 assists per game as a center — a feat almost unheard of at the position.",
      "Nicknamed 'The Joker' and is famously passionate about horses.",
    ],
  },
  {
    id: "giannis_c",
    name: "Giannis Antetokounmpo",
    aliases: ["giannis antetokounmpo", "giannis", "greek freak", "the greek freak"],
    teamColor: "#00471B",
    team: "Milwaukee Bucks",
    position: "PF",
    jersey: "34",
    clues: [
      "A forward who came from Greece and was selected 15th overall in the 2013 NBA Draft.",
      "Won back-to-back MVP awards and is known for his unstoppable drives to the basket.",
      "Led his team to the 2021 NBA championship and was named Finals MVP.",
      "Also won the Defensive Player of the Year award.",
      "Nicknamed 'The Greek Freak'.",
    ],
  },
  {
    id: "luka_c",
    name: "Luka Doncic",
    aliases: ["luka doncic", "luka", "doncic", "luka magic"],
    teamColor: "#552583",
    team: "Los Angeles Lakers",
    position: "PG",
    jersey: "77",
    clues: [
      "A Slovenian guard who won EuroLeague MVP at age 19 before coming to the NBA.",
      "Was Rookie of the Year in 2018-19 and has made the All-NBA First Team multiple times.",
      "Averages over 28 points, 8 rebounds, and 8 assists per game for his career.",
      "Was traded to a historic Los Angeles franchise midway through the 2024-25 season.",
      "Wears #77 and is known for his step-back three-pointer.",
    ],
  },
  {
    id: "sga",
    name: "Shai Gilgeous-Alexander",
    aliases: ["shai gilgeous-alexander", "sga", "shai", "gilgeous-alexander"],
    teamColor: "#007AC1",
    team: "Oklahoma City Thunder",
    position: "SG",
    jersey: "2",
    clues: [
      "A Canadian guard who has transformed a rebuilding franchise into a powerhouse.",
      "Won the scoring title in 2023-24 by averaging 30.1 points per game.",
      "Known for his silky smooth floater and ability to draw fouls at an elite rate.",
      "Has made multiple All-NBA First Teams and is considered one of the top 5 players in the league.",
      "Plays for a team in Oklahoma City wearing #2.",
    ],
  },
  {
    id: "tatum_c",
    name: "Jayson Tatum",
    aliases: ["jayson tatum", "tatum", "jt"],
    teamColor: "#007A33",
    team: "Boston Celtics",
    position: "SF",
    jersey: "0",
    clues: [
      "A forward from St. Louis who was drafted 3rd overall by a storied Boston franchise in 2017.",
      "Has been named an All-Star 6 times and consistently makes the All-NBA team.",
      "Won his first NBA championship in 2024 and was named Finals MVP.",
      "Averages around 27 points per game for his career on elite shooting splits.",
      "Wears #0 for the Boston Celtics.",
    ],
  },
  {
    id: "embiid_c",
    name: "Joel Embiid",
    aliases: ["joel embiid", "embiid", "the process", "jo"],
    teamColor: "#006BB6",
    team: "Philadelphia 76ers",
    position: "C",
    jersey: "21",
    clues: [
      "A center from Cameroon who only started playing basketball at age 16.",
      "Was the 3rd overall pick in the 2014 draft but missed his first two NBA seasons due to injury.",
      "Won the MVP award in 2022-23 and has led the league in scoring.",
      "Is known for his combination of dominant post play, mid-range shooting, and three-point ability.",
      "Nicknamed 'The Process' and plays for Philadelphia wearing #21.",
    ],
  },
  {
    id: "curry_c",
    name: "Stephen Curry",
    aliases: ["stephen curry", "steph curry", "curry", "steph", "chef curry"],
    teamColor: "#1D428A",
    team: "Golden State Warriors",
    position: "PG",
    jersey: "30",
    clues: [
      "A point guard widely credited with revolutionizing modern basketball through his long-range shooting.",
      "Has won 4 NBA championships and holds the all-time record for three-pointers made.",
      "Won the MVP award twice, including the first unanimous MVP vote in NBA history.",
      "Son of former NBA sharpshooter Dell Curry.",
      "Nicknamed 'Chef Curry' and plays for Golden State wearing #30.",
    ],
  },
  {
    id: "durant_c",
    name: "Kevin Durant",
    aliases: ["kevin durant", "durant", "kd", "slim reaper"],
    teamColor: "#1D1160",
    team: "Phoenix Suns",
    position: "SF",
    jersey: "35",
    clues: [
      "A 7-foot forward known as one of the most unguardable scorers in NBA history.",
      "Won 2 NBA championships and was named Finals MVP both times.",
      "Also won the MVP award and 4 scoring titles over his career.",
      "Famously left Oklahoma City for Golden State in 2016, sparking one of the biggest debates in NBA history.",
      "Nicknamed 'Slim Reaper' and currently wears #35.",
    ],
  },
  {
    id: "ad_c",
    name: "Anthony Davis",
    aliases: ["anthony davis", "ad", "the brow", "davis"],
    teamColor: "#552583",
    team: "Los Angeles Lakers",
    position: "C/PF",
    jersey: "3",
    clues: [
      "A big man from Chicago who was the #1 overall pick in the 2012 NBA Draft.",
      "Known for his rare combination of elite rim protection, rebounding, and offensive versatility.",
      "Won his first NBA championship in 2020 as a key piece of the Los Angeles Lakers.",
      "Has been named an All-Star 8 times and is a dominant two-way player.",
      "Nicknamed 'The Brow' for his prominent unibrow, wears #3 for the Lakers.",
    ],
  },
  {
    id: "ant_c",
    name: "Anthony Edwards",
    aliases: ["anthony edwards", "ant", "ant man", "edwards"],
    teamColor: "#236192",
    team: "Minnesota Timberwolves",
    position: "SG",
    jersey: "5",
    clues: [
      "A shooting guard who was the #1 overall pick in the 2020 NBA Draft out of Georgia.",
      "Known for his explosive athleticism, highlight dunks, and booming personality.",
      "Has quickly established himself as one of the best two-way wings in the league.",
      "Led his team to the Western Conference Finals in 2024.",
      "Nicknamed 'Ant-Man' and plays for Minnesota wearing #5.",
    ],
  },
  {
    id: "wemby_c",
    name: "Victor Wembanyama",
    aliases: ["victor wembanyama", "wembanyama", "wemby", "victor"],
    teamColor: "#C4CED4",
    team: "San Antonio Spurs",
    position: "C",
    jersey: "1",
    clues: [
      "A French center who was the #1 overall pick in the 2023 NBA Draft, hyped as a generational talent before entering the league.",
      "Stands 7'4\" with an enormous wingspan and guards all five positions while shooting threes.",
      "Won Rookie of the Year in 2023-24 and immediately became one of the league's most impactful players.",
      "Leads or is near the top of the league in blocked shots every season.",
      "Nicknamed 'Wemby' and plays for the San Antonio Spurs.",
    ],
  },
  {
    id: "ja_c",
    name: "Ja Morant",
    aliases: ["ja morant", "ja", "morant"],
    teamColor: "#5D76A9",
    team: "Memphis Grizzlies",
    position: "PG",
    jersey: "12",
    clues: [
      "A point guard from South Carolina who went 2nd overall in the 2019 NBA Draft.",
      "Won both Rookie of the Year and Most Improved Player in his first few seasons.",
      "Electrifies fans with his gravity-defying drives and acrobatic finishes at the rim.",
      "Averaged over 26 points and nearly 8 assists per game in the 2021-22 season.",
      "Plays for the Memphis Grizzlies wearing #12.",
    ],
  },
  {
    id: "trae_c",
    name: "Trae Young",
    aliases: ["trae young", "trae", "ice trae", "young"],
    teamColor: "#E03A3E",
    team: "Atlanta Hawks",
    position: "PG",
    jersey: "11",
    clues: [
      "A point guard from Oklahoma who plays with a style often compared to Stephen Curry.",
      "Was traded on draft night in 2018 as part of a deal involving Luka Doncic.",
      "Won the scoring title and leads the NBA in assists nearly every season.",
      "Led the Atlanta Hawks to the Eastern Conference Finals in 2021 as a 22-year-old.",
      "Nicknamed 'Ice Trae' and plays for Atlanta wearing #11.",
    ],
  },
  {
    id: "dame_c",
    name: "Damian Lillard",
    aliases: ["damian lillard", "dame", "lillard", "dame dolla"],
    teamColor: "#00471B",
    team: "Milwaukee Bucks",
    position: "PG",
    jersey: "0",
    clues: [
      "A point guard famous for his ability to hit game-winners from well beyond the three-point arc.",
      "Spent over a decade as the face of a Portland franchise before requesting a trade in 2023.",
      "Won a scoring title and has been named an All-Star 7 times.",
      "Currently teams up with another superstar in Milwaukee.",
      "Nicknamed 'Dame Dolla' and known for delivering in clutch moments.",
    ],
  },
  {
    id: "booker_c",
    name: "Devin Booker",
    aliases: ["devin booker", "booker", "book", "dbook"],
    teamColor: "#1D1160",
    team: "Phoenix Suns",
    position: "SG",
    jersey: "1",
    clues: [
      "A shooting guard who won an Olympic gold medal with Team USA in 2020 and 2024.",
      "Scored 70 points in a single game in March 2017 — at just 20 years old.",
      "Won the scoring title and has been an All-Star five times.",
      "The son of former NBA player Melvin Booker.",
      "Plays his entire career for Phoenix wearing #1.",
    ],
  },
];
