export interface CurrentNBAPlayer {
  id: string;
  name: string;
  aliases: string[];
  teamColor: string;
  team: string;
  position: string;
  jersey: string;
  draftYear: number | null; // null = undrafted
  draftPick: number | null; // null = undrafted
  ppg: number;
  rpg: number;
  apg: number;
  spg: number;
  bpg: number;
  age: number;
  height: number; // in inches (e.g. 78 = 6'6")
}

// Helper: null/null = undrafted
const u = null;

export const CURRENT_NBA_PLAYERS: CurrentNBAPlayer[] = [
  // ── ATLANTA HAWKS ──────────────────────────────────────────────────────────
  { id:"trae",      name:"Trae Young",            aliases:["trae young","trae","ice trae","young"],           teamColor:"#E03A3E", team:"Atlanta Hawks",           position:"PG", jersey:"11", draftYear:2018, draftPick:5,  ppg:26.2, rpg:3.9, apg:10.8, spg:1.0, bpg:0.1, age:27, height:73 },
  { id:"jjohnson",  name:"Jalen Johnson",          aliases:["jalen johnson","jalen","jj"],                    teamColor:"#E03A3E", team:"Atlanta Hawks",           position:"SF", jersey:"1",  draftYear:2021, draftPick:20, ppg:16.0, rpg:7.0, apg:3.5, spg:0.9, bpg:0.6, age:24, height:81 },
  { id:"dehunter",  name:"De'Andre Hunter",        aliases:["de'andre hunter","hunter","deandre hunter"],     teamColor:"#E03A3E", team:"Atlanta Hawks",           position:"SF", jersey:"12", draftYear:2019, draftPick:4,  ppg:13.0, rpg:3.5, apg:1.5, spg:1.1, bpg:0.4, age:26, height:79 },
  { id:"capela",    name:"Clint Capela",           aliases:["clint capela","capela"],                         teamColor:"#E03A3E", team:"Atlanta Hawks",           position:"C",  jersey:"15", draftYear:2014, draftPick:25, ppg:11.8, rpg:11.3, apg:1.2, spg:0.8, bpg:1.6, age:30, height:82 },
  { id:"okongwu",   name:"Onyeka Okongwu",         aliases:["onyeka okongwu","okongwu","onyeka"],             teamColor:"#E03A3E", team:"Atlanta Hawks",           position:"C",  jersey:"17", draftYear:2020, draftPick:6,  ppg:10.5, rpg:6.5, apg:1.2, spg:0.9, bpg:1.5, age:24, height:81 },
  { id:"bogdan",    name:"Bogdan Bogdanovic",       aliases:["bogdan bogdanovic","bogdan","bogdanovic"],       teamColor:"#E03A3E", team:"Atlanta Hawks",           position:"SG", jersey:"13", draftYear:2014, draftPick:27, ppg:14.0, rpg:2.5, apg:2.0, spg:0.8, bpg:0.2, age:32, height:78 },
  { id:"lnance",    name:"Larry Nance Jr.",         aliases:["larry nance jr","larry nance","nance"],         teamColor:"#E03A3E", team:"Atlanta Hawks",           position:"PF", jersey:"22", draftYear:2015, draftPick:27, ppg:8.5,  rpg:6.5, apg:2.5, spg:0.9, bpg:0.5, age:31, height:79 },
  { id:"ddaniels",  name:"Dyson Daniels",          aliases:["dyson daniels","daniels","dyson"],               teamColor:"#E03A3E", team:"Atlanta Hawks",           position:"SG", jersey:"5",  draftYear:2022, draftPick:8,  ppg:11.0, rpg:4.5, apg:3.5, spg:2.9, bpg:0.4, age:22, height:79 },
  { id:"gmathews",  name:"Garrison Mathews",       aliases:["garrison mathews","mathews"],                    teamColor:"#E03A3E", team:"Atlanta Hawks",           position:"SG", jersey:"20", draftYear:u,    draftPick:u,  ppg:6.0,  rpg:1.5, apg:0.5, spg:1.0, bpg:0.3, age:28, height:78 },
  { id:"krejci",    name:"Vit Krejci",             aliases:["vit krejci","krejci"],                           teamColor:"#E03A3E", team:"Atlanta Hawks",           position:"PG", jersey:"7",  draftYear:2021, draftPick:37, ppg:4.5,  rpg:2.0, apg:1.5, spg:1.1, bpg:0.2, age:24, height:81 },

  // ── BOSTON CELTICS ─────────────────────────────────────────────────────────
  { id:"tatum",     name:"Jayson Tatum",           aliases:["jayson tatum","tatum","jt"],                     teamColor:"#007A33", team:"Boston Celtics",          position:"SF", jersey:"0",  draftYear:2017, draftPick:3,  ppg:26.9, rpg:8.1, apg:4.9, spg:1.0, bpg:0.6, age:27, height:80 },
  { id:"jbrown",    name:"Jaylen Brown",           aliases:["jaylen brown","brown","jb"],                     teamColor:"#007A33", team:"Boston Celtics",          position:"SG", jersey:"7",  draftYear:2016, draftPick:3,  ppg:22.0, rpg:5.5, apg:3.5, spg:1.0, bpg:0.3, age:29, height:78 },
  { id:"holiday",   name:"Jrue Holiday",           aliases:["jrue holiday","holiday","jrue"],                 teamColor:"#007A33", team:"Boston Celtics",          position:"PG", jersey:"4",  draftYear:2009, draftPick:17, ppg:16.5, rpg:4.5, apg:5.0, spg:1.6, bpg:0.4, age:35, height:75 },
  { id:"horford",   name:"Al Horford",             aliases:["al horford","horford"],                          teamColor:"#007A33", team:"Boston Celtics",          position:"C",  jersey:"42", draftYear:2007, draftPick:3,  ppg:13.0, rpg:7.5, apg:3.5, spg:0.8, bpg:1.0, age:38, height:82 },
  { id:"porzingis", name:"Kristaps Porzingis",     aliases:["kristaps porzingis","porzingis","kp"],           teamColor:"#007A33", team:"Boston Celtics",          position:"C",  jersey:"8",  draftYear:2015, draftPick:4,  ppg:20.0, rpg:7.5, apg:2.0, spg:0.7, bpg:1.6, age:30, height:86 },
  { id:"dwhite",    name:"Derrick White",          aliases:["derrick white","white","d white"],               teamColor:"#007A33", team:"Boston Celtics",          position:"SG", jersey:"9",  draftYear:2017, draftPick:29, ppg:13.0, rpg:3.5, apg:3.5, spg:1.0, bpg:0.5, age:30, height:76 },
  { id:"ppritchard",name:"Payton Pritchard",       aliases:["payton pritchard","pritchard"],                  teamColor:"#007A33", team:"Boston Celtics",          position:"PG", jersey:"11", draftYear:2020, draftPick:26, ppg:9.0,  rpg:2.5, apg:2.5, spg:1.1, bpg:0.2, age:27, height:73 },
  { id:"shauser",   name:"Sam Hauser",             aliases:["sam hauser","hauser"],                           teamColor:"#007A33", team:"Boston Celtics",          position:"SF", jersey:"30", draftYear:2021, draftPick:54, ppg:13.0, rpg:3.0, apg:1.0, spg:0.9, bpg:0.5, age:26, height:79 },
  { id:"kornet",    name:"Luke Kornet",            aliases:["luke kornet","kornet"],                          teamColor:"#007A33", team:"Boston Celtics",          position:"C",  jersey:"2",  draftYear:u,    draftPick:u,  ppg:5.5,  rpg:3.0, apg:0.8, spg:0.6, bpg:1.4, age:28, height:85 },
  { id:"xtillman",  name:"Xavier Tillman",         aliases:["xavier tillman","tillman","xt"],                 teamColor:"#007A33", team:"Boston Celtics",          position:"PF", jersey:"26", draftYear:2020, draftPick:35, ppg:5.5,  rpg:4.0, apg:1.0, spg:0.8, bpg:0.9, age:26, height:80 },

  // ── BROOKLYN NETS ──────────────────────────────────────────────────────────
  { id:"camthomas", name:"Cam Thomas",             aliases:["cam thomas","thomas","cameron thomas"],          teamColor:"#000000", team:"Brooklyn Nets",           position:"SG", jersey:"24", draftYear:2021, draftPick:27, ppg:21.0, rpg:3.5, apg:2.5, spg:1.0, bpg:0.3, age:23, height:79 },
  { id:"nclaxton",  name:"Nic Claxton",            aliases:["nic claxton","claxton","nicolas claxton"],       teamColor:"#000000", team:"Brooklyn Nets",           position:"C",  jersey:"33", draftYear:2019, draftPick:31, ppg:12.0, rpg:9.0, apg:2.5, spg:0.9, bpg:2.0, age:25, height:83 },
  { id:"cjohnson",  name:"Cameron Johnson",        aliases:["cameron johnson","cam johnson","johnson"],       teamColor:"#000000", team:"Brooklyn Nets",           position:"SF", jersey:"2",  draftYear:2019, draftPick:11, ppg:14.0, rpg:4.5, apg:2.0, spg:0.9, bpg:0.5, age:27, height:80 },
  { id:"schroder",  name:"Dennis Schroder",        aliases:["dennis schroder","schroder","dennis"],          teamColor:"#000000", team:"Brooklyn Nets",           position:"PG", jersey:"17", draftYear:2013, draftPick:17, ppg:15.0, rpg:3.0, apg:5.5, spg:1.1, bpg:0.2, age:32, height:73 },
  { id:"bsimmons",  name:"Ben Simmons",            aliases:["ben simmons","simmons","bens"],                  teamColor:"#000000", team:"Brooklyn Nets",           position:"PG", jersey:"10", draftYear:2016, draftPick:1,  ppg:15.9, rpg:7.9, apg:7.7, spg:1.6, bpg:0.6, age:29, height:82 },
  { id:"dfssmith",  name:"Dorian Finney-Smith",    aliases:["dorian finney-smith","finney-smith","dfs"],      teamColor:"#000000", team:"Brooklyn Nets",           position:"SF", jersey:"28", draftYear:u,    draftPick:u,  ppg:9.5,  rpg:4.5, apg:1.5, spg:0.9, bpg:0.5, age:32, height:79 },
  { id:"clowney",   name:"Noah Clowney",           aliases:["noah clowney","clowney"],                        teamColor:"#000000", team:"Brooklyn Nets",           position:"PF", jersey:"21", draftYear:2023, draftPick:21, ppg:9.0,  rpg:5.5, apg:1.0, spg:0.8, bpg:0.9, age:23, height:81 },
  { id:"drsharpe",  name:"Day'Ron Sharpe",         aliases:["day'ron sharpe","sharpe","dayron sharpe"],       teamColor:"#000000", team:"Brooklyn Nets",           position:"C",  jersey:"20", draftYear:2021, draftPick:29, ppg:8.5,  rpg:7.0, apg:1.0, spg:0.6, bpg:1.4, age:25, height:82 },
  { id:"bpodziemski",name:"Brandin Podziemski",    aliases:["brandin podziemski","podziemski"],               teamColor:"#000000", team:"Brooklyn Nets",           position:"SG", jersey:"8",  draftYear:2023, draftPick:19, ppg:9.5,  rpg:4.5, apg:3.5, spg:1.0, bpg:0.3, age:23, height:76 },

  // ── CHARLOTTE HORNETS ──────────────────────────────────────────────────────
  { id:"lamelo",    name:"LaMelo Ball",            aliases:["lamelo ball","lamelo","melo"],                   teamColor:"#1D1160", team:"Charlotte Hornets",       position:"PG", jersey:"1",  draftYear:2020, draftPick:3,  ppg:22.0, rpg:5.5, apg:7.5, spg:1.5, bpg:0.4, age:24, height:79 },
  { id:"bmiller",   name:"Brandon Miller",         aliases:["brandon miller","miller","bm"],                  teamColor:"#1D1160", team:"Charlotte Hornets",       position:"SF", jersey:"24", draftYear:2023, draftPick:2,  ppg:17.0, rpg:4.5, apg:2.5, spg:0.9, bpg:0.5, age:23, height:81 },
  { id:"mbridges",  name:"Miles Bridges",          aliases:["miles bridges","bridges","mb"],                  teamColor:"#1D1160", team:"Charlotte Hornets",       position:"SF", jersey:"0",  draftYear:2018, draftPick:12, ppg:19.0, rpg:6.0, apg:3.0, spg:1.2, bpg:0.7, age:27, height:78 },
  { id:"mwilliams", name:"Mark Williams",          aliases:["mark williams","williams","mwill"],              teamColor:"#1D1160", team:"Charlotte Hornets",       position:"C",  jersey:"5",  draftYear:2022, draftPick:15, ppg:12.0, rpg:9.0, apg:1.0, spg:0.6, bpg:1.4, age:24, height:84 },
  { id:"gwilliams", name:"Grant Williams",         aliases:["grant williams","grant","gwilliams"],            teamColor:"#1D1160", team:"Charlotte Hornets",       position:"PF", jersey:"2",  draftYear:2019, draftPick:22, ppg:9.5,  rpg:4.0, apg:1.5, spg:0.8, bpg:0.9, age:27, height:79 },
  { id:"nrichards", name:"Nick Richards",          aliases:["nick richards","richards"],                      teamColor:"#1D1160", team:"Charlotte Hornets",       position:"C",  jersey:"4",  draftYear:2020, draftPick:42, ppg:8.0,  rpg:6.5, apg:0.5, spg:0.6, bpg:1.4, age:26, height:83 },
  { id:"tsalaun",   name:"Tidjane Salaun",         aliases:["tidjane salaun","salaun"],                       teamColor:"#1D1160", team:"Charlotte Hornets",       position:"SF", jersey:"6",  draftYear:2024, draftPick:6,  ppg:6.5,  rpg:3.0, apg:1.0, spg:0.9, bpg:0.5, age:22, height:81 },
  { id:"tremann",   name:"Tre Mann",               aliases:["tre mann","mann"],                               teamColor:"#1D1160", team:"Charlotte Hornets",       position:"SG", jersey:"23", draftYear:2021, draftPick:18, ppg:11.0, rpg:2.5, apg:2.0, spg:1.0, bpg:0.3, age:25, height:78 },
  { id:"jgreen",    name:"Josh Green",             aliases:["josh green","green","jgreen"],                   teamColor:"#1D1160", team:"Charlotte Hornets",       position:"SG", jersey:"8",  draftYear:2020, draftPick:18, ppg:9.5,  rpg:3.0, apg:2.0, spg:1.0, bpg:0.3, age:26, height:79 },

  // ── CHICAGO BULLS ──────────────────────────────────────────────────────────
  { id:"lavine",    name:"Zach LaVine",            aliases:["zach lavine","lavine","zach"],                   teamColor:"#CE1141", team:"Chicago Bulls",           position:"SG", jersey:"8",  draftYear:2014, draftPick:13, ppg:23.0, rpg:4.5, apg:4.5, spg:1.0, bpg:0.3, age:32, height:77 },
  { id:"vucevic",   name:"Nikola Vucevic",         aliases:["nikola vucevic","vucevic","vooch"],              teamColor:"#CE1141", team:"Chicago Bulls",           position:"C",  jersey:"9",  draftYear:2011, draftPick:16, ppg:17.0, rpg:10.5, apg:3.0, spg:0.6, bpg:1.4, age:35, height:84 },
  { id:"cwhite",    name:"Coby White",             aliases:["coby white","white","coby"],                     teamColor:"#CE1141", team:"Chicago Bulls",           position:"PG", jersey:"0",  draftYear:2019, draftPick:7,  ppg:16.0, rpg:3.5, apg:4.5, spg:1.1, bpg:0.2, age:24, height:76 },
  { id:"pwilliams", name:"Patrick Williams",       aliases:["patrick williams","pat williams"],               teamColor:"#CE1141", team:"Chicago Bulls",           position:"SF", jersey:"44", draftYear:2020, draftPick:4,  ppg:12.0, rpg:5.5, apg:2.0, spg:0.9, bpg:0.5, age:26, height:81 },
  { id:"giddey",    name:"Josh Giddey",            aliases:["josh giddey","giddey"],                          teamColor:"#CE1141", team:"Chicago Bulls",           position:"PG", jersey:"3",  draftYear:2021, draftPick:6,  ppg:14.0, rpg:7.5, apg:6.5, spg:1.1, bpg:0.2, age:22, height:80 },
  { id:"dosunmu",   name:"Ayo Dosunmu",            aliases:["ayo dosunmu","dosunmu","ayo"],                   teamColor:"#CE1141", team:"Chicago Bulls",           position:"SG", jersey:"12", draftYear:2021, draftPick:38, ppg:11.0, rpg:3.5, apg:3.0, spg:1.0, bpg:0.3, age:25, height:77 },
  { id:"mbuzelis",  name:"Matas Buzelis",          aliases:["matas buzelis","buzelis"],                       teamColor:"#CE1141", team:"Chicago Bulls",           position:"SF", jersey:"14", draftYear:2024, draftPick:11, ppg:8.0,  rpg:3.5, apg:1.0, spg:0.9, bpg:0.5, age:22, height:84 },
  { id:"adrummond", name:"Andre Drummond",         aliases:["andre drummond","drummond"],                     teamColor:"#CE1141", team:"Chicago Bulls",           position:"C",  jersey:"3",  draftYear:2012, draftPick:9,  ppg:14.0, rpg:13.5, apg:1.5, spg:0.6, bpg:1.4, age:34, height:82 },
  { id:"tporter",   name:"Terry Porter",           aliases:["terquavion smith","tsmith","tq"],                teamColor:"#CE1141", team:"Chicago Bulls",           position:"SG", jersey:"0",  draftYear:2023, draftPick:25, ppg:8.5,  rpg:2.0, apg:1.5, spg:1.0, bpg:0.3, age:23, height:78 },

  // ── CLEVELAND CAVALIERS ────────────────────────────────────────────────────
  { id:"dmitchell", name:"Donovan Mitchell",       aliases:["donovan mitchell","mitchell","spida"],           teamColor:"#6F263D", team:"Cleveland Cavaliers",     position:"SG", jersey:"45", draftYear:2017, draftPick:13, ppg:25.6, rpg:4.2, apg:5.0, spg:1.0, bpg:0.3, age:29, height:73 },
  { id:"garland",   name:"Darius Garland",         aliases:["darius garland","garland"],                     teamColor:"#6F263D", team:"Cleveland Cavaliers",     position:"PG", jersey:"10", draftYear:2019, draftPick:5,  ppg:21.0, rpg:3.0, apg:6.5, spg:1.1, bpg:0.2, age:27, height:73 },
  { id:"mobley",    name:"Evan Mobley",            aliases:["evan mobley","mobley"],                          teamColor:"#6F263D", team:"Cleveland Cavaliers",     position:"C",  jersey:"4",  draftYear:2021, draftPick:3,  ppg:17.0, rpg:9.5, apg:2.5, spg:0.6, bpg:1.4, age:25, height:83 },
  { id:"jallen",    name:"Jarrett Allen",          aliases:["jarrett allen","allen","jallen"],                teamColor:"#6F263D", team:"Cleveland Cavaliers",     position:"C",  jersey:"31", draftYear:2017, draftPick:22, ppg:13.0, rpg:10.5, apg:1.5, spg:1.0, bpg:1.2, age:26, height:82 },
  { id:"clevert",   name:"Caris LeVert",           aliases:["caris levert","levert"],                        teamColor:"#6F263D", team:"Cleveland Cavaliers",     position:"SG", jersey:"3",  draftYear:2016, draftPick:20, ppg:15.0, rpg:3.5, apg:3.5, spg:1.0, bpg:0.3, age:30, height:79 },
  { id:"mstrus",    name:"Max Strus",              aliases:["max strus","strus"],                             teamColor:"#6F263D", team:"Cleveland Cavaliers",     position:"SG", jersey:"1",  draftYear:u,    draftPick:u,  ppg:12.0, rpg:3.0, apg:1.5, spg:1.0, bpg:0.3, age:28, height:78 },
  { id:"gniang",    name:"Georges Niang",          aliases:["georges niang","niang"],                         teamColor:"#6F263D", team:"Cleveland Cavaliers",     position:"PF", jersey:"20", draftYear:2016, draftPick:49, ppg:10.0, rpg:3.5, apg:1.5, spg:0.8, bpg:0.9, age:30, height:80 },
  { id:"dwade2",    name:"Dean Wade",              aliases:["dean wade","wade","dwade"],                      teamColor:"#6F263D", team:"Cleveland Cavaliers",     position:"PF", jersey:"32", draftYear:u,    draftPick:u,  ppg:7.0,  rpg:3.5, apg:1.0, spg:0.8, bpg:0.9, age:28, height:82 },
  { id:"tyjerome",  name:"Ty Jerome",              aliases:["ty jerome","jerome"],                            teamColor:"#6F263D", team:"Cleveland Cavaliers",     position:"PG", jersey:"13", draftYear:u,    draftPick:u,  ppg:9.0,  rpg:2.0, apg:3.0, spg:1.1, bpg:0.2, age:28, height:75 },

  // ── DALLAS MAVERICKS ───────────────────────────────────────────────────────
  { id:"kyrie",     name:"Kyrie Irving",           aliases:["kyrie irving","kyrie","uncle drew"],             teamColor:"#00538C", team:"Dallas Mavericks",        position:"PG", jersey:"11", draftYear:2011, draftPick:1,  ppg:23.6, rpg:3.8, apg:5.7, spg:1.1, bpg:0.2, age:33, height:74 },
  { id:"ad",        name:"Anthony Davis",          aliases:["anthony davis","ad","the brow","davis"],         teamColor:"#00538C", team:"Dallas Mavericks",        position:"C",  jersey:"3",  draftYear:2012, draftPick:1,  ppg:23.8, rpg:10.3, apg:2.7, spg:0.6, bpg:1.4, age:34, height:82 },
  { id:"kthompson", name:"Klay Thompson",          aliases:["klay thompson","klay","splash brother"],         teamColor:"#00538C", team:"Dallas Mavericks",        position:"SG", jersey:"31", draftYear:2011, draftPick:11, ppg:19.3, rpg:3.7, apg:2.3, spg:1.0, bpg:0.3, age:35, height:78 },
  { id:"pjwash",    name:"P.J. Washington",        aliases:["p.j. washington","pj washington","washington"],  teamColor:"#00538C", team:"Dallas Mavericks",        position:"PF", jersey:"25", draftYear:2019, draftPick:12, ppg:11.0, rpg:5.5, apg:1.5, spg:0.8, bpg:0.9, age:27, height:80 },
  { id:"dlively",   name:"Dereck Lively II",       aliases:["dereck lively","lively","dereck lively ii"],     teamColor:"#00538C", team:"Dallas Mavericks",        position:"C",  jersey:"2",  draftYear:2023, draftPick:12, ppg:9.5,  rpg:7.5, apg:1.5, spg:0.6, bpg:1.4, age:23, height:84 },
  { id:"dgafford",  name:"Daniel Gafford",         aliases:["daniel gafford","gafford"],                      teamColor:"#00538C", team:"Dallas Mavericks",        position:"C",  jersey:"21", draftYear:2019, draftPick:38, ppg:10.0, rpg:6.5, apg:1.0, spg:0.6, bpg:1.4, age:27, height:82 },
  { id:"qgrimes",   name:"Quentin Grimes",         aliases:["quentin grimes","grimes"],                       teamColor:"#00538C", team:"Dallas Mavericks",        position:"SG", jersey:"5",  draftYear:2021, draftPick:25, ppg:10.5, rpg:3.0, apg:1.5, spg:1.0, bpg:0.3, age:25, height:78 },
  { id:"sdinwiddie",name:"Spencer Dinwiddie",      aliases:["spencer dinwiddie","dinwiddie"],                 teamColor:"#00538C", team:"Dallas Mavericks",        position:"PG", jersey:"26", draftYear:2014, draftPick:38, ppg:15.0, rpg:3.5, apg:5.5, spg:1.1, bpg:0.2, age:32, height:76 },
  { id:"mchristie", name:"Max Christie",           aliases:["max christie","christie"],                       teamColor:"#00538C", team:"Dallas Mavericks",        position:"SG", jersey:"7",  draftYear:2022, draftPick:35, ppg:7.0,  rpg:2.5, apg:1.0, spg:1.0, bpg:0.3, age:24, height:78 },

  // ── DENVER NUGGETS ─────────────────────────────────────────────────────────
  { id:"jokic",     name:"Nikola Jokic",           aliases:["nikola jokic","jokic","the joker","joker"],      teamColor:"#FEC524", team:"Denver Nuggets",          position:"C",  jersey:"15", draftYear:2014, draftPick:41, ppg:26.4, rpg:12.4, apg:9.0, spg:1.3, bpg:0.7, age:30, height:84 },
  { id:"jmurray",   name:"Jamal Murray",           aliases:["jamal murray","murray","murray"],                teamColor:"#FEC524", team:"Denver Nuggets",          position:"PG", jersey:"27", draftYear:2016, draftPick:7,  ppg:18.0, rpg:4.0, apg:5.0, spg:1.1, bpg:0.2, age:30, height:76 },
  { id:"mporter",   name:"Michael Porter Jr.",     aliases:["michael porter jr","mporter","mpj"],             teamColor:"#FEC524", team:"Denver Nuggets",          position:"SF", jersey:"1",  draftYear:2018, draftPick:14, ppg:16.0, rpg:7.0, apg:1.5, spg:0.9, bpg:0.5, age:28, height:82 },
  { id:"agordon",   name:"Aaron Gordon",           aliases:["aaron gordon","gordon","ag"],                    teamColor:"#FEC524", team:"Denver Nuggets",          position:"PF", jersey:"50", draftYear:2014, draftPick:4,  ppg:13.0, rpg:6.5, apg:3.0, spg:0.8, bpg:0.9, age:32, height:80 },
  { id:"kcpp",      name:"Kentavious Caldwell-Pope",aliases:["kentavious caldwell-pope","kcp","caldwell-pope"],teamColor:"#FEC524", team:"Denver Nuggets",          position:"SG", jersey:"5",  draftYear:2013, draftPick:8,  ppg:11.0, rpg:3.0, apg:1.5, spg:1.0, bpg:0.3, age:31, height:77 },
  { id:"cbraun",    name:"Christian Braun",        aliases:["christian braun","braun"],                       teamColor:"#FEC524", team:"Denver Nuggets",          position:"SG", jersey:"0",  draftYear:2022, draftPick:21, ppg:9.5,  rpg:3.5, apg:1.5, spg:1.0, bpg:0.3, age:24, height:78 },
  { id:"pwatson",   name:"Peyton Watson",          aliases:["peyton watson","watson"],                        teamColor:"#FEC524", team:"Denver Nuggets",          position:"SF", jersey:"8",  draftYear:2022, draftPick:30, ppg:6.5,  rpg:3.0, apg:0.8, spg:0.9, bpg:0.5, age:24, height:81 },
  { id:"znnaji",    name:"Zeke Nnaji",             aliases:["zeke nnaji","nnaji"],                            teamColor:"#FEC524", team:"Denver Nuggets",          position:"PF", jersey:"22", draftYear:2020, draftPick:22, ppg:5.5,  rpg:4.0, apg:0.5, spg:0.8, bpg:0.9, age:26, height:82 },
  { id:"rjackson",  name:"Reggie Jackson",         aliases:["reggie jackson","jackson","reggie"],             teamColor:"#FEC524", team:"Denver Nuggets",          position:"PG", jersey:"7",  draftYear:2011, draftPick:24, ppg:13.5, rpg:3.0, apg:4.5, spg:1.1, bpg:0.2, age:35, height:75 },

  // ── GOLDEN STATE WARRIORS ──────────────────────────────────────────────────
  { id:"curry",     name:"Stephen Curry",          aliases:["stephen curry","steph curry","curry","steph","chef curry"], teamColor:"#1D428A", team:"Golden State Warriors", position:"PG", jersey:"30", draftYear:2009, draftPick:7,  ppg:24.8, rpg:4.6, apg:6.4, spg:1.4, bpg:0.2, age:37, height:74 },
  { id:"jbutler",   name:"Jimmy Butler",           aliases:["jimmy butler","butler","jimmy","jimmy buckets"],  teamColor:"#1D428A", team:"Golden State Warriors",   position:"SF", jersey:"22", draftYear:2011, draftPick:30, ppg:19.2, rpg:5.8, apg:4.2, spg:1.8, bpg:0.5, age:36, height:79 },
  { id:"dgreen",    name:"Draymond Green",         aliases:["draymond green","draymond","green"],             teamColor:"#1D428A", team:"Golden State Warriors",   position:"PF", jersey:"23", draftYear:2012, draftPick:35, ppg:8.5,  rpg:7.5, apg:7.5, spg:1.4, bpg:0.6, age:35, height:79 },
  { id:"awiggins",  name:"Andrew Wiggins",         aliases:["andrew wiggins","wiggins"],                      teamColor:"#1D428A", team:"Golden State Warriors",   position:"SF", jersey:"22", draftYear:2014, draftPick:1,  ppg:17.5, rpg:4.5, apg:2.5, spg:0.9, bpg:0.5, age:32, height:80 },
  { id:"kuminga",   name:"Jonathan Kuminga",       aliases:["jonathan kuminga","kuminga","jk"],               teamColor:"#1D428A", team:"Golden State Warriors",   position:"SF", jersey:"00", draftYear:2021, draftPick:7,  ppg:15.0, rpg:5.0, apg:1.5, spg:0.8, bpg:0.5, age:22, height:80 },
  { id:"mmoody",    name:"Moses Moody",            aliases:["moses moody","moody"],                           teamColor:"#1D428A", team:"Golden State Warriors",   position:"SG", jersey:"4",  draftYear:2021, draftPick:14, ppg:10.0, rpg:3.0, apg:1.0, spg:1.0, bpg:0.3, age:25, height:78 },
  { id:"gpaytonii", name:"Gary Payton II",         aliases:["gary payton ii","gary payton","gp2"],            teamColor:"#1D428A", team:"Golden State Warriors",   position:"SG", jersey:"8",  draftYear:u,    draftPick:u,  ppg:8.5,  rpg:3.0, apg:1.5, spg:1.0, bpg:0.3, age:28, height:73 },
  { id:"tjdavis",   name:"Trayce Jackson-Davis",   aliases:["trayce jackson-davis","trayce","tjd"],           teamColor:"#1D428A", team:"Golden State Warriors",   position:"C",  jersey:"32", draftYear:2023, draftPick:57, ppg:8.5,  rpg:5.5, apg:1.5, spg:0.6, bpg:1.4, age:23, height:81 },

  // ── HOUSTON ROCKETS ────────────────────────────────────────────────────────
  { id:"sengun",    name:"Alperen Sengun",         aliases:["alperen sengun","sengun","alp"],                 teamColor:"#CE1141", team:"Houston Rockets",         position:"C",  jersey:"28", draftYear:2021, draftPick:16, ppg:19.0, rpg:9.5, apg:4.0, spg:1.0, bpg:1.2, age:22, height:83 },
  { id:"jgreen2",   name:"Jalen Green",            aliases:["jalen green","green","jg"],                      teamColor:"#CE1141", team:"Houston Rockets",         position:"SG", jersey:"4",  draftYear:2021, draftPick:2,  ppg:21.0, rpg:4.0, apg:4.0, spg:1.0, bpg:0.3, age:34, height:76 },
  { id:"athompson", name:"Amen Thompson",          aliases:["amen thompson","amen","thompson"],               teamColor:"#CE1141", team:"Houston Rockets",         position:"SF", jersey:"1",  draftYear:2023, draftPick:4,  ppg:16.0, rpg:7.0, apg:4.5, spg:0.9, bpg:0.5, age:23, height:81 },
  { id:"jsmith",    name:"Jabari Smith Jr.",       aliases:["jabari smith jr","jabari smith","jabari"],       teamColor:"#CE1141", team:"Houston Rockets",         position:"PF", jersey:"10", draftYear:2022, draftPick:3,  ppg:13.0, rpg:7.0, apg:1.5, spg:0.8, bpg:0.9, age:24, height:82 },
  { id:"fvv",       name:"Fred VanVleet",          aliases:["fred vanvleet","vanvleet","fvv"],                 teamColor:"#CE1141", team:"Houston Rockets",         position:"PG", jersey:"5",  draftYear:u,    draftPick:u,  ppg:17.0, rpg:3.5, apg:6.5, spg:1.4, bpg:0.5, age:28, height:78 },
  { id:"dbrooks",   name:"Dillon Brooks",          aliases:["dillon brooks","brooks","dillon"],               teamColor:"#CE1141", team:"Houston Rockets",         position:"SF", jersey:"11", draftYear:2017, draftPick:45, ppg:14.0, rpg:3.5, apg:2.0, spg:0.9, bpg:0.5, age:29, height:76 },
  { id:"teason",    name:"Tari Eason",             aliases:["tari eason","eason"],                            teamColor:"#CE1141", team:"Houston Rockets",         position:"SF", jersey:"17", draftYear:2022, draftPick:17, ppg:10.0, rpg:5.0, apg:1.0, spg:0.9, bpg:0.5, age:24, height:80 },
  { id:"cwhitmore", name:"Cam Whitmore",           aliases:["cam whitmore","whitmore"],                       teamColor:"#CE1141", team:"Houston Rockets",         position:"SF", jersey:"26", draftYear:2023, draftPick:20, ppg:11.5, rpg:4.0, apg:1.0, spg:0.9, bpg:0.5, age:23, height:81 },
  { id:"jaeseant",  name:"Jae'Sean Tate",          aliases:["jae'sean tate","tate","jaesean tate"],           teamColor:"#CE1141", team:"Houston Rockets",         position:"SF", jersey:"8",  draftYear:u,    draftPick:u,  ppg:9.5,  rpg:4.5, apg:2.0, spg:0.9, bpg:0.5, age:28, height:80 },

  // ── INDIANA PACERS ─────────────────────────────────────────────────────────
  { id:"haliburton",name:"Tyrese Haliburton",      aliases:["tyrese haliburton","haliburton","tyrese"],       teamColor:"#002D62", team:"Indiana Pacers",          position:"PG", jersey:"0",  draftYear:2020, draftPick:12, ppg:20.0, rpg:4.0, apg:10.5, spg:1.4, bpg:0.3, age:25, height:76 },
  { id:"siakam",    name:"Pascal Siakam",          aliases:["pascal siakam","siakam","spicy p"],              teamColor:"#002D62", team:"Indiana Pacers",          position:"PF", jersey:"43", draftYear:2016, draftPick:27, ppg:18.0, rpg:6.5, apg:3.5, spg:0.9, bpg:0.6, age:31, height:81 },
  { id:"mturner",   name:"Myles Turner",           aliases:["myles turner","turner","myles"],                 teamColor:"#002D62", team:"Indiana Pacers",          position:"C",  jersey:"33", draftYear:2015, draftPick:11, ppg:13.0, rpg:6.5, apg:1.5, spg:0.6, bpg:1.4, age:31, height:84 },
  { id:"bmathurin", name:"Bennedict Mathurin",     aliases:["bennedict mathurin","mathurin","ben mathurin"],  teamColor:"#002D62", team:"Indiana Pacers",          position:"SG", jersey:"00", draftYear:2022, draftPick:6,  ppg:15.0, rpg:4.0, apg:1.5, spg:1.0, bpg:0.3, age:24, height:78 },
  { id:"anesmith",  name:"Aaron Nesmith",          aliases:["aaron nesmith","nesmith"],                       teamColor:"#002D62", team:"Indiana Pacers",          position:"SF", jersey:"23", draftYear:2020, draftPick:14, ppg:12.0, rpg:5.0, apg:2.0, spg:0.9, bpg:0.5, age:26, height:78 },
  { id:"otoppin",   name:"Obi Toppin",             aliases:["obi toppin","toppin","obi"],                     teamColor:"#002D62", team:"Indiana Pacers",          position:"PF", jersey:"1",  draftYear:2020, draftPick:8,  ppg:12.0, rpg:4.5, apg:1.0, spg:0.8, bpg:0.9, age:26, height:80 },
  { id:"tjmcconn",  name:"T.J. McConnell",         aliases:["t.j. mcconnell","mcconnell","tj mcconnell"],     teamColor:"#002D62", team:"Indiana Pacers",          position:"PG", jersey:"9",  draftYear:u,    draftPick:u,  ppg:8.5,  rpg:3.0, apg:5.0, spg:1.1, bpg:0.2, age:28, height:73 },
  { id:"anembhard", name:"Andrew Nembhard",        aliases:["andrew nembhard","nembhard"],                    teamColor:"#002D62", team:"Indiana Pacers",          position:"PG", jersey:"2",  draftYear:u,    draftPick:u,  ppg:10.0, rpg:3.5, apg:5.0, spg:1.1, bpg:0.2, age:28, height:76 },
  { id:"jwalker",   name:"Jarace Walker",          aliases:["jarace walker","walker"],                        teamColor:"#002D62", team:"Indiana Pacers",          position:"PF", jersey:"5",  draftYear:2023, draftPick:8,  ppg:8.5,  rpg:4.5, apg:1.5, spg:0.8, bpg:0.9, age:23, height:80 },
  { id:"bsheppard", name:"Ben Sheppard",           aliases:["ben sheppard","sheppard"],                       teamColor:"#002D62", team:"Indiana Pacers",          position:"SG", jersey:"26", draftYear:2023, draftPick:26, ppg:9.5,  rpg:3.0, apg:2.0, spg:1.0, bpg:0.3, age:23, height:78 },

  // ── LOS ANGELES CLIPPERS ───────────────────────────────────────────────────
  { id:"kawhi",     name:"Kawhi Leonard",          aliases:["kawhi leonard","kawhi","the klaw","leonard"],    teamColor:"#C8102E", team:"Los Angeles Clippers",    position:"SF", jersey:"2",  draftYear:2011, draftPick:15, ppg:19.7, rpg:6.5, apg:3.6, spg:1.7, bpg:0.4, age:34, height:79 },
  { id:"harden",    name:"James Harden",           aliases:["james harden","harden","the beard"],             teamColor:"#C8102E", team:"Los Angeles Clippers",    position:"PG", jersey:"1",  draftYear:2009, draftPick:3,  ppg:25.0, rpg:5.4, apg:7.1, spg:1.4, bpg:0.6, age:36, height:77 },
  { id:"npowell",   name:"Norman Powell",          aliases:["norman powell","powell","norm"],                 teamColor:"#C8102E", team:"Los Angeles Clippers",    position:"SG", jersey:"24", draftYear:2015, draftPick:46, ppg:13.0, rpg:2.5, apg:1.5, spg:1.0, bpg:0.3, age:31, height:79 },
  { id:"zubac",     name:"Ivica Zubac",            aliases:["ivica zubac","zubac"],                           teamColor:"#C8102E", team:"Los Angeles Clippers",    position:"C",  jersey:"40", draftYear:2016, draftPick:32, ppg:12.0, rpg:9.5, apg:1.5, spg:0.6, bpg:1.4, age:30, height:85 },
  { id:"tmann",     name:"Terance Mann",           aliases:["terance mann","mann","terance"],                 teamColor:"#C8102E", team:"Los Angeles Clippers",    position:"SF", jersey:"14", draftYear:2020, draftPick:48, ppg:9.5,  rpg:3.5, apg:1.5, spg:0.9, bpg:0.5, age:28, height:78 },
  { id:"nbatum",    name:"Nicolas Batum",          aliases:["nicolas batum","batum","nic batum"],             teamColor:"#C8102E", team:"Los Angeles Clippers",    position:"SF", jersey:"33", draftYear:2008, draftPick:25, ppg:8.5,  rpg:4.5, apg:2.5, spg:0.9, bpg:0.5, age:38, height:80 },
  { id:"bhyland",   name:"Bones Hyland",          aliases:["bones hyland","hyland","bones"],                  teamColor:"#C8102E", team:"Los Angeles Clippers",    position:"PG", jersey:"5",  draftYear:2021, draftPick:26, ppg:11.0, rpg:2.5, apg:3.0, spg:1.1, bpg:0.2, age:25, height:75 },
  { id:"jmiller",   name:"Jordan Miller",          aliases:["jordan miller","miller"],                        teamColor:"#C8102E", team:"Los Angeles Clippers",    position:"SF", jersey:"10", draftYear:2023, draftPick:37, ppg:7.5,  rpg:3.0, apg:1.0, spg:0.9, bpg:0.5, age:23, height:79 },

  // ── LOS ANGELES LAKERS ─────────────────────────────────────────────────────
  { id:"lebron",    name:"LeBron James",           aliases:["lebron james","lebron","king james","the king","king"], teamColor:"#552583", team:"Los Angeles Lakers", position:"SF", jersey:"23", draftYear:2003, draftPick:1,  ppg:27.2, rpg:7.5, apg:7.4, spg:1.3, bpg:0.6, age:41, height:81 },
  { id:"luka",      name:"Luka Doncic",            aliases:["luka doncic","luka","doncic","luka magic"],      teamColor:"#552583", team:"Los Angeles Lakers",      position:"PG", jersey:"77", draftYear:2018, draftPick:3,  ppg:28.7, rpg:8.7, apg:8.3, spg:1.1, bpg:0.2, age:26, height:79 },
  { id:"areaves",   name:"Austin Reaves",          aliases:["austin reaves","reaves","ar"],                   teamColor:"#552583", team:"Los Angeles Lakers",      position:"SG", jersey:"15", draftYear:u,    draftPick:u,  ppg:15.0, rpg:3.5, apg:4.0, spg:1.0, bpg:0.3, age:28, height:77 },
  { id:"hachimura", name:"Rui Hachimura",          aliases:["rui hachimura","hachimura","rui"],               teamColor:"#552583", team:"Los Angeles Lakers",      position:"SF", jersey:"28", draftYear:2019, draftPick:9,  ppg:12.0, rpg:4.5, apg:1.0, spg:0.9, bpg:0.5, age:27, height:80 },
  { id:"dknecht",   name:"Dalton Knecht",          aliases:["dalton knecht","knecht"],                        teamColor:"#552583", team:"Los Angeles Lakers",      position:"SG", jersey:"4",  draftYear:2024, draftPick:17, ppg:9.5,  rpg:3.0, apg:1.0, spg:1.0, bpg:0.3, age:22, height:80 },
  { id:"bronny",    name:"Bronny James",           aliases:["bronny james","bronny","bronny james"],          teamColor:"#552583", team:"Los Angeles Lakers",      position:"SG", jersey:"9",  draftYear:2024, draftPick:55, ppg:3.5,  rpg:1.5, apg:1.0, spg:1.0, bpg:0.3, age:22, height:74 },
  { id:"jvanderbilt",name:"Jarred Vanderbilt",     aliases:["jarred vanderbilt","vanderbilt"],                teamColor:"#552583", team:"Los Angeles Lakers",      position:"PF", jersey:"2",  draftYear:2018, draftPick:41, ppg:7.5,  rpg:5.5, apg:1.5, spg:0.8, bpg:0.9, age:28, height:81 },
  { id:"gvincent",  name:"Gabe Vincent",           aliases:["gabe vincent","vincent"],                        teamColor:"#552583", team:"Los Angeles Lakers",      position:"PG", jersey:"7",  draftYear:u,    draftPick:u,  ppg:9.5,  rpg:2.0, apg:2.5, spg:1.1, bpg:0.2, age:28, height:76 },
  { id:"dlrussell", name:"D'Angelo Russell",       aliases:["d'angelo russell","russell","dlo"],              teamColor:"#552583", team:"Los Angeles Lakers",      position:"PG", jersey:"1",  draftYear:2015, draftPick:2,  ppg:17.5, rpg:3.0, apg:5.5, spg:1.1, bpg:0.2, age:31, height:76 },

  // ── MEMPHIS GRIZZLIES ──────────────────────────────────────────────────────
  { id:"ja",        name:"Ja Morant",              aliases:["ja morant","ja","morant"],                       teamColor:"#5D76A9", team:"Memphis Grizzlies",       position:"PG", jersey:"12", draftYear:2019, draftPick:2,  ppg:22.7, rpg:5.6, apg:7.9, spg:1.1, bpg:0.2, age:27, height:74 },
  { id:"jjackson",  name:"Jaren Jackson Jr.",      aliases:["jaren jackson jr","jaren jackson","jjj"],        teamColor:"#5D76A9", team:"Memphis Grizzlies",       position:"C",  jersey:"13", draftYear:2018, draftPick:4,  ppg:19.0, rpg:6.5, apg:1.5, spg:0.6, bpg:1.4, age:28, height:83 },
  { id:"dbane",     name:"Desmond Bane",           aliases:["desmond bane","bane","des"],                     teamColor:"#5D76A9", team:"Memphis Grizzlies",       position:"SG", jersey:"22", draftYear:2020, draftPick:30, ppg:20.0, rpg:4.5, apg:4.0, spg:1.0, bpg:0.3, age:26, height:78 },
  { id:"msmart",    name:"Marcus Smart",           aliases:["marcus smart","smart","marcus"],                 teamColor:"#5D76A9", team:"Memphis Grizzlies",       position:"PG", jersey:"36", draftYear:2014, draftPick:6,  ppg:11.0, rpg:3.5, apg:5.5, spg:1.1, bpg:0.2, age:32, height:75 },
  { id:"zwilliams", name:"Ziaire Williams",        aliases:["ziaire williams","ziaire"],                      teamColor:"#5D76A9", team:"Memphis Grizzlies",       position:"SF", jersey:"21", draftYear:2021, draftPick:10, ppg:10.0, rpg:3.5, apg:1.5, spg:0.9, bpg:0.5, age:25, height:80 },
  { id:"saldama",   name:"Santi Aldama",           aliases:["santi aldama","aldama","santi"],                 teamColor:"#5D76A9", team:"Memphis Grizzlies",       position:"PF", jersey:"7",  draftYear:2021, draftPick:30, ppg:10.0, rpg:5.0, apg:2.0, spg:0.8, bpg:0.9, age:25, height:81 },
  { id:"ggjackson", name:"GG Jackson II",          aliases:["gg jackson","gg jackson ii","ggjackson"],        teamColor:"#5D76A9", team:"Memphis Grizzlies",       position:"PF", jersey:"45", draftYear:2023, draftPick:18, ppg:12.0, rpg:4.5, apg:1.5, spg:0.8, bpg:0.9, age:23, height:81 },
  { id:"zebdey",    name:"Zach Edey",              aliases:["zach edey","edey"],                              teamColor:"#5D76A9", team:"Memphis Grizzlies",       position:"C",  jersey:"14", draftYear:2024, draftPick:9,  ppg:10.0, rpg:8.5, apg:1.0, spg:0.6, bpg:1.4, age:22, height:85 },
  { id:"laraviad",  name:"Jake LaRavia",           aliases:["jake laravia","laravia"],                        teamColor:"#5D76A9", team:"Memphis Grizzlies",       position:"SF", jersey:"3",  draftYear:2022, draftPick:19, ppg:9.0,  rpg:4.0, apg:2.0, spg:0.9, bpg:0.5, age:24, height:79 },

  // ── MIAMI HEAT ─────────────────────────────────────────────────────────────
  { id:"bam",       name:"Bam Adebayo",            aliases:["bam adebayo","bam","adebayo"],                   teamColor:"#98002E", team:"Miami Heat",              position:"C",  jersey:"13", draftYear:2017, draftPick:14, ppg:19.2, rpg:10.0, apg:3.8, spg:0.6, bpg:1.4, age:29, height:81 },
  { id:"therro",    name:"Tyler Herro",            aliases:["tyler herro","herro","tyler"],                   teamColor:"#98002E", team:"Miami Heat",              position:"SG", jersey:"14", draftYear:2019, draftPick:13, ppg:19.0, rpg:5.0, apg:4.5, spg:0.9, bpg:0.3, age:25, height:77 },
  { id:"trozier",   name:"Terry Rozier",           aliases:["terry rozier","rozier","scary terry"],           teamColor:"#98002E", team:"Miami Heat",              position:"PG", jersey:"2",  draftYear:2015, draftPick:16, ppg:18.0, rpg:4.5, apg:4.5, spg:1.1, bpg:0.2, age:31, height:73 },
  { id:"njovic",    name:"Nikola Jovic",           aliases:["nikola jovic","jovic"],                          teamColor:"#98002E", team:"Miami Heat",              position:"PF", jersey:"5",  draftYear:2022, draftPick:27, ppg:10.0, rpg:4.5, apg:2.5, spg:0.8, bpg:0.9, age:24, height:82 },
  { id:"drobinson", name:"Duncan Robinson",        aliases:["duncan robinson","robinson","dunk"],             teamColor:"#98002E", team:"Miami Heat",              position:"SF", jersey:"55", draftYear:u,    draftPick:u,  ppg:13.0, rpg:3.0, apg:1.5, spg:0.9, bpg:0.5, age:28, height:78 },
  { id:"jjaquez",   name:"Jaime Jaquez Jr.",       aliases:["jaime jaquez jr","jaquez","jaime jaquez"],       teamColor:"#98002E", team:"Miami Heat",              position:"SF", jersey:"11", draftYear:2023, draftPick:18, ppg:12.0, rpg:4.5, apg:2.0, spg:0.9, bpg:0.5, age:23, height:79 },
  { id:"hhighsmith",name:"Haywood Highsmith",      aliases:["haywood highsmith","highsmith"],                 teamColor:"#98002E", team:"Miami Heat",              position:"SF", jersey:"24", draftYear:u,    draftPick:u,  ppg:8.0,  rpg:3.5, apg:1.0, spg:0.9, bpg:0.5, age:28, height:80 },
  { id:"orobinson", name:"Orlando Robinson",       aliases:["orlando robinson","or robinson"],                teamColor:"#98002E", team:"Miami Heat",              position:"C",  jersey:"00", draftYear:2022, draftPick:54, ppg:6.0,  rpg:4.5, apg:0.8, spg:0.6, bpg:1.4, age:24, height:84 },

  // ── MILWAUKEE BUCKS ────────────────────────────────────────────────────────
  { id:"giannis",   name:"Giannis Antetokounmpo",  aliases:["giannis antetokounmpo","giannis","greek freak","the greek freak"], teamColor:"#00471B", team:"Milwaukee Bucks", position:"PF", jersey:"34", draftYear:2013, draftPick:15, ppg:29.2, rpg:11.7, apg:5.8, spg:1.2, bpg:1.2, age:31, height:83 },
  { id:"dame",      name:"Damian Lillard",         aliases:["damian lillard","dame","lillard","dame dolla"],  teamColor:"#00471B", team:"Milwaukee Bucks",         position:"PG", jersey:"0",  draftYear:2012, draftPick:6,  ppg:24.7, rpg:4.2, apg:6.9, spg:1.1, bpg:0.2, age:34, height:74 },
  { id:"kmiddleton",name:"Khris Middleton",        aliases:["khris middleton","middleton","khris"],           teamColor:"#00471B", team:"Milwaukee Bucks",         position:"SF", jersey:"22", draftYear:2012, draftPick:39, ppg:17.0, rpg:5.0, apg:4.5, spg:0.9, bpg:0.5, age:34, height:79 },
  { id:"blopez",    name:"Brook Lopez",            aliases:["brook lopez","lopez","brook"],                   teamColor:"#00471B", team:"Milwaukee Bucks",         position:"C",  jersey:"11", draftYear:2008, draftPick:10, ppg:14.0, rpg:4.5, apg:1.5, spg:0.6, bpg:1.4, age:38, height:84 },
  { id:"bportis",   name:"Bobby Portis",           aliases:["bobby portis","portis","bobby"],                 teamColor:"#00471B", team:"Milwaukee Bucks",         position:"PF", jersey:"9",  draftYear:2015, draftPick:22, ppg:13.0, rpg:7.5, apg:1.0, spg:0.8, bpg:0.9, age:31, height:80 },
  { id:"mbeasley",  name:"Malik Beasley",          aliases:["malik beasley","beasley","malik"],               teamColor:"#00471B", team:"Milwaukee Bucks",         position:"SG", jersey:"5",  draftYear:2016, draftPick:19, ppg:15.0, rpg:3.0, apg:1.5, spg:1.0, bpg:0.3, age:30, height:77 },
  { id:"mjbeauchamp",name:"MarJon Beauchamp",      aliases:["marjon beauchamp","beauchamp","marjon"],         teamColor:"#00471B", team:"Milwaukee Bucks",         position:"SF", jersey:"6",  draftYear:2022, draftPick:24, ppg:7.5,  rpg:3.5, apg:1.0, spg:0.9, bpg:0.5, age:24, height:80 },
  { id:"ajgreen2",  name:"A.J. Green",             aliases:["a.j. green","aj green","green"],                 teamColor:"#00471B", team:"Milwaukee Bucks",         position:"SG", jersey:"14", draftYear:u,    draftPick:u,  ppg:8.5,  rpg:2.0, apg:1.0, spg:1.0, bpg:0.3, age:28, height:76 },

  // ── MINNESOTA TIMBERWOLVES ─────────────────────────────────────────────────
  { id:"ant",       name:"Anthony Edwards",        aliases:["anthony edwards","ant","ant man","edwards"],     teamColor:"#236192", team:"Minnesota Timberwolves",  position:"SG", jersey:"5",  draftYear:2020, draftPick:1,  ppg:24.6, rpg:5.4, apg:4.9, spg:1.0, bpg:0.3, age:26, height:76 },
  { id:"gobert",    name:"Rudy Gobert",            aliases:["rudy gobert","gobert","rudy"],                   teamColor:"#236192", team:"Minnesota Timberwolves",  position:"C",  jersey:"27", draftYear:2013, draftPick:27, ppg:14.0, rpg:12.5, apg:2.0, spg:0.7, bpg:2.1, age:33, height:85 },
  { id:"jrandle",   name:"Julius Randle",          aliases:["julius randle","randle","julius"],               teamColor:"#236192", team:"Minnesota Timberwolves",  position:"PF", jersey:"30", draftYear:2014, draftPick:7,  ppg:22.0, rpg:9.0, apg:4.5, spg:0.8, bpg:0.9, age:32, height:81 },
  { id:"jmcdaniels",name:"Jaden McDaniels",        aliases:["jaden mcdaniels","mcdaniels","jaden"],           teamColor:"#236192", team:"Minnesota Timberwolves",  position:"SF", jersey:"3",  draftYear:2020, draftPick:28, ppg:14.0, rpg:4.5, apg:1.5, spg:0.9, bpg:0.5, age:26, height:80 },
  { id:"nreid",     name:"Naz Reid",               aliases:["naz reid","reid","naz"],                         teamColor:"#236192", team:"Minnesota Timberwolves",  position:"C",  jersey:"11", draftYear:u,    draftPick:u,  ppg:14.0, rpg:5.5, apg:1.5, spg:0.6, bpg:1.4, age:28, height:83 },
  { id:"nawilliams",name:"Nickeil Alexander-Walker",aliases:["nickeil alexander-walker","naw","nickeil"],     teamColor:"#236192", team:"Minnesota Timberwolves",  position:"SG", jersey:"9",  draftYear:2019, draftPick:17, ppg:12.0, rpg:3.0, apg:2.5, spg:1.0, bpg:0.3, age:27, height:80 },
  { id:"rdillingham",name:"Rob Dillingham",        aliases:["rob dillingham","dillingham","rob"],             teamColor:"#236192", team:"Minnesota Timberwolves",  position:"PG", jersey:"10", draftYear:2024, draftPick:8,  ppg:8.5,  rpg:2.0, apg:3.0, spg:1.1, bpg:0.2, age:22, height:74 },
  { id:"mconley",   name:"Mike Conley",            aliases:["mike conley","conley","mike"],                   teamColor:"#236192", team:"Minnesota Timberwolves",  position:"PG", jersey:"10", draftYear:2007, draftPick:4,  ppg:14.0, rpg:3.0, apg:5.5, spg:1.1, bpg:0.2, age:39, height:73 },

  // ── NEW ORLEANS PELICANS ───────────────────────────────────────────────────
  { id:"zion",      name:"Zion Williamson",        aliases:["zion williamson","zion","williamson"],           teamColor:"#002B5C", team:"New Orleans Pelicans",    position:"PF", jersey:"1",  draftYear:2019, draftPick:1,  ppg:25.7, rpg:7.0, apg:3.8, spg:0.8, bpg:0.9, age:24, height:78 },
  { id:"bingram",   name:"Brandon Ingram",         aliases:["brandon ingram","ingram","bi"],                  teamColor:"#002B5C", team:"New Orleans Pelicans",    position:"SF", jersey:"14", draftYear:2016, draftPick:2,  ppg:22.0, rpg:5.5, apg:3.5, spg:0.9, bpg:0.5, age:30, height:81 },
  { id:"cjmcc",     name:"CJ McCollum",            aliases:["cj mccollum","mccollum","cj"],                   teamColor:"#002B5C", team:"New Orleans Pelicans",    position:"SG", jersey:"3",  draftYear:2013, draftPick:10, ppg:19.0, rpg:4.5, apg:4.5, spg:1.0, bpg:0.3, age:33, height:75 },
  { id:"dmurray2",  name:"Dejounte Murray",        aliases:["dejounte murray","dejounte","murray"],           teamColor:"#002B5C", team:"New Orleans Pelicans",    position:"SG", jersey:"5",  draftYear:2016, draftPick:29, ppg:18.5, rpg:5.5, apg:5.3, spg:1.0, bpg:0.3, age:30, height:77 },
  { id:"tmurphy",   name:"Trey Murphy III",        aliases:["trey murphy iii","trey murphy","murphy"],       teamColor:"#002B5C", team:"New Orleans Pelicans",    position:"SF", jersey:"25", draftYear:2021, draftPick:17, ppg:17.0, rpg:4.5, apg:1.5, spg:0.9, bpg:0.5, age:25, height:81 },
  { id:"hjones",    name:"Herb Jones",             aliases:["herb jones","jones","herb"],                     teamColor:"#002B5C", team:"New Orleans Pelicans",    position:"SF", jersey:"5",  draftYear:2021, draftPick:35, ppg:11.0, rpg:4.5, apg:2.5, spg:0.9, bpg:0.5, age:25, height:79 },
  { id:"jalvarado", name:"Jose Alvarado",          aliases:["jose alvarado","alvarado","jose"],               teamColor:"#002B5C", team:"New Orleans Pelicans",    position:"PG", jersey:"15", draftYear:u,    draftPick:u,  ppg:9.0,  rpg:2.5, apg:3.0, spg:1.1, bpg:0.2, age:28, height:72 },
  { id:"jhawkins",  name:"Jordan Hawkins",         aliases:["jordan hawkins","hawkins"],                      teamColor:"#002B5C", team:"New Orleans Pelicans",    position:"SG", jersey:"10", draftYear:2023, draftPick:14, ppg:10.0, rpg:2.5, apg:1.0, spg:1.0, bpg:0.3, age:23, height:78 },
  { id:"ymissi",    name:"Yves Missi",             aliases:["yves missi","missi"],                            teamColor:"#002B5C", team:"New Orleans Pelicans",    position:"C",  jersey:"21", draftYear:2024, draftPick:21, ppg:7.5,  rpg:6.0, apg:0.8, spg:0.6, bpg:1.4, age:22, height:84 },

  // ── NEW YORK KNICKS ────────────────────────────────────────────────────────
  { id:"brunson",   name:"Jalen Brunson",          aliases:["jalen brunson","brunson","jb"],                  teamColor:"#F58426", team:"New York Knicks",         position:"PG", jersey:"11", draftYear:2018, draftPick:33, ppg:22.1, rpg:3.3, apg:6.2, spg:1.1, bpg:0.2, age:28, height:73 },
  { id:"kat",       name:"Karl-Anthony Towns",     aliases:["karl-anthony towns","kat","towns"],              teamColor:"#F58426", team:"New York Knicks",         position:"C",  jersey:"32", draftYear:2015, draftPick:1,  ppg:22.7, rpg:10.8, apg:3.2, spg:0.6, bpg:1.4, age:31, height:84 },
  { id:"oganunoby", name:"OG Anunoby",             aliases:["og anunoby","anunoby","og"],                     teamColor:"#F58426", team:"New York Knicks",         position:"SF", jersey:"8",  draftYear:2017, draftPick:23, ppg:16.0, rpg:5.0, apg:2.0, spg:0.9, bpg:0.5, age:29, height:80 },
  { id:"mikalbridg",name:"Mikal Bridges",          aliases:["mikal bridges","bridges","mikal"],               teamColor:"#F58426", team:"New York Knicks",         position:"SF", jersey:"7",  draftYear:2018, draftPick:10, ppg:19.0, rpg:4.0, apg:2.5, spg:0.9, bpg:0.5, age:28, height:79 },
  { id:"jhart",     name:"Josh Hart",              aliases:["josh hart","hart","josh"],                       teamColor:"#F58426", team:"New York Knicks",         position:"SF", jersey:"3",  draftYear:2017, draftPick:30, ppg:10.0, rpg:8.5, apg:4.0, spg:0.9, bpg:0.5, age:29, height:78 },
  { id:"ddivincenzo",name:"Donte DiVincenzo",      aliases:["donte divincenzo","divincenzo","donte"],         teamColor:"#F58426", team:"New York Knicks",         position:"SG", jersey:"0",  draftYear:2018, draftPick:17, ppg:12.0, rpg:3.0, apg:3.0, spg:1.0, bpg:0.3, age:28, height:77 },
  { id:"mrobinson", name:"Mitchell Robinson",      aliases:["mitchell robinson","robinson","mitch"],          teamColor:"#F58426", team:"New York Knicks",         position:"C",  jersey:"23", draftYear:2018, draftPick:36, ppg:10.5, rpg:8.5, apg:0.8, spg:0.6, bpg:1.4, age:28, height:84 },
  { id:"mmcbride",  name:"Miles McBride",          aliases:["miles mcbride","mcbride","deuce"],               teamColor:"#F58426", team:"New York Knicks",         position:"PG", jersey:"2",  draftYear:2021, draftPick:36, ppg:10.0, rpg:2.5, apg:2.5, spg:1.1, bpg:0.2, age:25, height:75 },
  { id:"pachiuwa",  name:"Precious Achiuwa",       aliases:["precious achiuwa","achiuwa","precious"],         teamColor:"#F58426", team:"New York Knicks",         position:"PF", jersey:"5",  draftYear:2020, draftPick:20, ppg:9.5,  rpg:6.5, apg:1.0, spg:0.8, bpg:0.9, age:26, height:80 },

  // ── OKLAHOMA CITY THUNDER ──────────────────────────────────────────────────
  { id:"sga",       name:"Shai Gilgeous-Alexander",aliases:["shai gilgeous-alexander","sga","shai"],          teamColor:"#007AC1", team:"Oklahoma City Thunder",   position:"SG", jersey:"2",  draftYear:2018, draftPick:11, ppg:24.5, rpg:4.6, apg:5.9, spg:2.0, bpg:1.0, age:27, height:78 },
  { id:"cholmgren", name:"Chet Holmgren",          aliases:["chet holmgren","holmgren","chet"],               teamColor:"#007AC1", team:"Oklahoma City Thunder",   position:"C",  jersey:"7",  draftYear:2022, draftPick:2,  ppg:17.5, rpg:7.8, apg:2.2, spg:0.6, bpg:1.4, age:24, height:85 },
  { id:"jwilliams2",name:"Jalen Williams",         aliases:["jalen williams","j-dub","jwilliams"],            teamColor:"#007AC1", team:"Oklahoma City Thunder",   position:"SG", jersey:"8",  draftYear:2022, draftPick:12, ppg:21.0, rpg:4.5, apg:4.5, spg:1.0, bpg:0.3, age:24, height:78 },
  { id:"ldort",     name:"Lu Dort",                aliases:["lu dort","dort","luguentz dort"],                teamColor:"#007AC1", team:"Oklahoma City Thunder",   position:"SG", jersey:"5",  draftYear:u,    draftPick:u,  ppg:15.0, rpg:4.0, apg:2.0, spg:1.3, bpg:0.5, age:30, height:76 },
  { id:"ihartenstein",name:"Isaiah Hartenstein",   aliases:["isaiah hartenstein","hartenstein"],              teamColor:"#007AC1", team:"Oklahoma City Thunder",   position:"C",  jersey:"55", draftYear:2017, draftPick:43, ppg:10.0, rpg:9.0, apg:2.5, spg:0.6, bpg:1.4, age:29, height:84 },
  { id:"acaruso",   name:"Alex Caruso",            aliases:["alex caruso","caruso","ac"],                     teamColor:"#007AC1", team:"Oklahoma City Thunder",   position:"SG", jersey:"6",  draftYear:u,    draftPick:u,  ppg:9.5,  rpg:3.5, apg:3.0, spg:1.0, bpg:0.3, age:28, height:77 },
  { id:"awiggins2", name:"Aaron Wiggins",          aliases:["aaron wiggins","wiggins"],                       teamColor:"#007AC1", team:"Oklahoma City Thunder",   position:"SG", jersey:"21", draftYear:2021, draftPick:55, ppg:9.0,  rpg:3.0, apg:1.5, spg:1.0, bpg:0.3, age:25, height:78 },
  { id:"kwilliams", name:"Kenrich Williams",       aliases:["kenrich williams","kenrich"],                    teamColor:"#007AC1", team:"Oklahoma City Thunder",   position:"SF", jersey:"34", draftYear:u,    draftPick:u,  ppg:8.0,  rpg:4.5, apg:2.0, spg:0.9, bpg:0.5, age:28, height:78 },
  { id:"isaiahj",   name:"Isaiah Joe",             aliases:["isaiah joe","joe"],                              teamColor:"#007AC1", team:"Oklahoma City Thunder",   position:"SG", jersey:"11", draftYear:2020, draftPick:49, ppg:9.0,  rpg:2.5, apg:1.5, spg:1.0, bpg:0.3, age:26, height:75 },

  // ── ORLANDO MAGIC ──────────────────────────────────────────────────────────
  { id:"banchero",  name:"Paolo Banchero",         aliases:["paolo banchero","banchero","paolo"],             teamColor:"#0077C0", team:"Orlando Magic",           position:"PF", jersey:"5",  draftYear:2022, draftPick:1,  ppg:22.6, rpg:6.9, apg:4.7, spg:0.8, bpg:0.9, age:24, height:82 },
  { id:"fwagner",   name:"Franz Wagner",           aliases:["franz wagner","wagner","franz"],                 teamColor:"#0077C0", team:"Orlando Magic",           position:"SF", jersey:"21", draftYear:2021, draftPick:8,  ppg:21.0, rpg:5.5, apg:3.5, spg:0.9, bpg:0.5, age:25, height:80 },
  { id:"jsuggs",    name:"Jalen Suggs",            aliases:["jalen suggs","suggs","jalen"],                   teamColor:"#0077C0", team:"Orlando Magic",           position:"PG", jersey:"4",  draftYear:2021, draftPick:5,  ppg:15.0, rpg:4.0, apg:4.5, spg:1.1, bpg:0.2, age:23, height:78 },
  { id:"wcarterj",  name:"Wendell Carter Jr.",     aliases:["wendell carter jr","wendell carter","wcj"],      teamColor:"#0077C0", team:"Orlando Magic",           position:"C",  jersey:"34", draftYear:2018, draftPick:7,  ppg:12.0, rpg:8.0, apg:2.0, spg:0.6, bpg:1.4, age:28, height:83 },
  { id:"canthony",  name:"Cole Anthony",           aliases:["cole anthony","anthony","cole"],                 teamColor:"#0077C0", team:"Orlando Magic",           position:"PG", jersey:"50", draftYear:2020, draftPick:15, ppg:12.0, rpg:4.5, apg:4.0, spg:1.1, bpg:0.2, age:26, height:77 },
  { id:"jisaac",    name:"Jonathan Isaac",         aliases:["jonathan isaac","isaac","jonathan"],             teamColor:"#0077C0", team:"Orlando Magic",           position:"PF", jersey:"1",  draftYear:2017, draftPick:6,  ppg:9.0,  rpg:5.5, apg:1.0, spg:0.8, bpg:0.9, age:29, height:81 },
  { id:"anthonyblack",name:"Anthony Black",        aliases:["anthony black","black"],                         teamColor:"#0077C0", team:"Orlando Magic",           position:"PG", jersey:"0",  draftYear:2023, draftPick:6,  ppg:10.0, rpg:4.0, apg:3.5, spg:1.1, bpg:0.2, age:23, height:79 },
  { id:"tdasilva",  name:"Tristan da Silva",       aliases:["tristan da silva","da silva","tristan"],         teamColor:"#0077C0", team:"Orlando Magic",           position:"SF", jersey:"16", draftYear:2024, draftPick:18, ppg:8.5,  rpg:3.5, apg:1.5, spg:0.9, bpg:0.5, age:22, height:82 },
  { id:"mwagner",   name:"Moritz Wagner",          aliases:["moritz wagner","moe wagner","mwagner"],          teamColor:"#0077C0", team:"Orlando Magic",           position:"C",  jersey:"21", draftYear:2018, draftPick:25, ppg:12.0, rpg:5.0, apg:1.5, spg:0.6, bpg:1.4, age:28, height:82 },
  { id:"gharris",   name:"Gary Harris",            aliases:["gary harris","harris"],                          teamColor:"#0077C0", team:"Orlando Magic",           position:"SG", jersey:"14", draftYear:2014, draftPick:19, ppg:12.0, rpg:2.5, apg:2.0, spg:1.0, bpg:0.3, age:32, height:78 },

  // ── PHILADELPHIA 76ERS ─────────────────────────────────────────────────────
  { id:"embiid",    name:"Joel Embiid",            aliases:["joel embiid","embiid","the process","jo"],       teamColor:"#006BB6", team:"Philadelphia 76ers",      position:"C",  jersey:"21", draftYear:2014, draftPick:3,  ppg:27.5, rpg:11.2, apg:3.7, spg:1.0, bpg:1.7, age:31, height:84 },
  { id:"pgeorge",   name:"Paul George",            aliases:["paul george","pg","pg13","george"],              teamColor:"#006BB6", team:"Philadelphia 76ers",      position:"SF", jersey:"8",  draftYear:2010, draftPick:10, ppg:20.1, rpg:5.7, apg:3.5, spg:0.9, bpg:0.5, age:36, height:80 },
  { id:"tmaxey",    name:"Tyrese Maxey",           aliases:["tyrese maxey","maxey","tyrese"],                 teamColor:"#006BB6", team:"Philadelphia 76ers",      position:"PG", jersey:"0",  draftYear:2020, draftPick:21, ppg:21.0, rpg:3.5, apg:5.0, spg:1.1, bpg:0.2, age:26, height:75 },
  { id:"koubre",    name:"Kelly Oubre Jr.",        aliases:["kelly oubre jr","oubre","kelly oubre"],          teamColor:"#006BB6", team:"Philadelphia 76ers",      position:"SF", jersey:"12", draftYear:2015, draftPick:15, ppg:14.0, rpg:5.0, apg:1.5, spg:0.9, bpg:0.5, age:31, height:78 },
  { id:"egordon",   name:"Eric Gordon",            aliases:["eric gordon","gordon","eg"],                     teamColor:"#006BB6", team:"Philadelphia 76ers",      position:"SG", jersey:"23", draftYear:2008, draftPick:7,  ppg:15.0, rpg:2.5, apg:2.0, spg:1.0, bpg:0.3, age:38, height:75 },
  { id:"kjmartin",  name:"KJ Martin",              aliases:["kj martin","martin","kenyon martin jr"],         teamColor:"#006BB6", team:"Philadelphia 76ers",      position:"SF", jersey:"1",  draftYear:u,    draftPick:u,  ppg:10.0, rpg:4.5, apg:1.0, spg:0.9, bpg:0.5, age:28, height:80 },
  { id:"cmartin",   name:"Caleb Martin",           aliases:["caleb martin","caleb"],                          teamColor:"#006BB6", team:"Philadelphia 76ers",      position:"SF", jersey:"16", draftYear:u,    draftPick:u,  ppg:9.5,  rpg:4.5, apg:1.5, spg:0.9, bpg:0.5, age:28, height:78 },
  { id:"adrummond2",name:"Andre Drummond",         aliases:["andre drummond","drummond"],                     teamColor:"#006BB6", team:"Philadelphia 76ers",      position:"C",  jersey:"4",  draftYear:2012, draftPick:9,  ppg:14.0, rpg:13.5, apg:1.5, spg:0.6, bpg:1.4, age:34, height:82 },

  // ── PHOENIX SUNS ───────────────────────────────────────────────────────────
  { id:"durant",    name:"Kevin Durant",           aliases:["kevin durant","durant","kd","slim reaper"],      teamColor:"#1D1160", team:"Phoenix Suns",            position:"SF", jersey:"35", draftYear:2007, draftPick:2,  ppg:27.3, rpg:7.0, apg:4.4, spg:0.9, bpg:0.5, age:39, height:82 },
  { id:"booker",    name:"Devin Booker",           aliases:["devin booker","booker","book","dbook"],          teamColor:"#1D1160", team:"Phoenix Suns",            position:"SG", jersey:"1",  draftYear:2015, draftPick:13, ppg:23.5, rpg:4.5, apg:4.7, spg:1.0, bpg:0.3, age:31, height:78 },
  { id:"bbeal",     name:"Bradley Beal",           aliases:["bradley beal","beal","brad"],                    teamColor:"#1D1160", team:"Phoenix Suns",            position:"SG", jersey:"3",  draftYear:2012, draftPick:3,  ppg:22.1, rpg:3.8, apg:3.8, spg:1.0, bpg:0.3, age:34, height:76 },
  { id:"nurkic",    name:"Jusuf Nurkic",           aliases:["jusuf nurkic","nurkic","nurk"],                  teamColor:"#1D1160", team:"Phoenix Suns",            position:"C",  jersey:"20", draftYear:2014, draftPick:16, ppg:12.0, rpg:10.5, apg:3.0, spg:0.6, bpg:1.4, age:32, height:84 },
  { id:"gallen",    name:"Grayson Allen",          aliases:["grayson allen","allen","grayson"],               teamColor:"#1D1160", team:"Phoenix Suns",            position:"SG", jersey:"8",  draftYear:2018, draftPick:21, ppg:11.0, rpg:3.0, apg:2.0, spg:1.0, bpg:0.3, age:28, height:78 },
  { id:"rdunn",     name:"Ryan Dunn",              aliases:["ryan dunn","dunn"],                              teamColor:"#1D1160", team:"Phoenix Suns",            position:"SF", jersey:"10", draftYear:2024, draftPick:10, ppg:8.0,  rpg:3.5, apg:1.5, spg:0.9, bpg:0.5, age:22, height:79 },
  { id:"roneale",   name:"Royce O'Neale",          aliases:["royce o'neale","o'neale","royce"],               teamColor:"#1D1160", team:"Phoenix Suns",            position:"SF", jersey:"14", draftYear:u,    draftPick:u,  ppg:9.5,  rpg:4.5, apg:2.0, spg:0.9, bpg:0.5, age:28, height:79 },
  { id:"oighodaro", name:"Oso Ighodaro",           aliases:["oso ighodaro","ighodaro","oso"],                 teamColor:"#1D1160", team:"Phoenix Suns",            position:"C",  jersey:"15", draftYear:2024, draftPick:31, ppg:6.0,  rpg:4.5, apg:1.0, spg:0.6, bpg:1.4, age:22, height:82 },

  // ── PORTLAND TRAIL BLAZERS ─────────────────────────────────────────────────
  { id:"shenderson",name:"Scoot Henderson",        aliases:["scoot henderson","scoot","henderson"],           teamColor:"#E03A3E", team:"Portland Trail Blazers",  position:"PG", jersey:"0",  draftYear:2023, draftPick:3,  ppg:14.0, rpg:4.0, apg:6.5, spg:1.1, bpg:0.2, age:23, height:75 },
  { id:"asimons",   name:"Anfernee Simons",        aliases:["anfernee simons","simons","ant simons"],         teamColor:"#E03A3E", team:"Portland Trail Blazers",  position:"SG", jersey:"1",  draftYear:2018, draftPick:24, ppg:21.0, rpg:3.5, apg:5.0, spg:1.0, bpg:0.3, age:28, height:76 },
  { id:"ssharpe",   name:"Shaedon Sharpe",         aliases:["shaedon sharpe","sharpe","shaedon"],             teamColor:"#E03A3E", team:"Portland Trail Blazers",  position:"SG", jersey:"17", draftYear:2022, draftPick:7,  ppg:17.0, rpg:4.0, apg:2.0, spg:1.0, bpg:0.3, age:24, height:79 },
  { id:"jgrant",    name:"Jerami Grant",           aliases:["jerami grant","grant","jerami"],                 teamColor:"#E03A3E", team:"Portland Trail Blazers",  position:"SF", jersey:"9",  draftYear:2014, draftPick:39, ppg:17.0, rpg:4.0, apg:2.0, spg:0.9, bpg:0.5, age:32, height:81 },
  { id:"dayton",    name:"Deandre Ayton",          aliases:["deandre ayton","ayton","da"],                    teamColor:"#E03A3E", team:"Portland Trail Blazers",  position:"C",  jersey:"2",  draftYear:2018, draftPick:1,  ppg:16.5, rpg:10.0, apg:1.5, spg:0.6, bpg:1.4, age:28, height:83 },
  { id:"tcamara",   name:"Toumani Camara",         aliases:["toumani camara","camara","toumani"],             teamColor:"#E03A3E", team:"Portland Trail Blazers",  position:"SF", jersey:"33", draftYear:2023, draftPick:32, ppg:9.0,  rpg:4.5, apg:1.5, spg:0.9, bpg:0.5, age:23, height:79 },
  { id:"mthybulle", name:"Matisse Thybulle",       aliases:["matisse thybulle","thybulle","matisse"],         teamColor:"#E03A3E", team:"Portland Trail Blazers",  position:"SF", jersey:"4",  draftYear:2019, draftPick:20, ppg:8.0,  rpg:3.0, apg:1.5, spg:0.9, bpg:0.5, age:27, height:78 },
  { id:"rrupert",   name:"Rayan Rupert",           aliases:["rayan rupert","rupert","rayan"],                 teamColor:"#E03A3E", team:"Portland Trail Blazers",  position:"SF", jersey:"10", draftYear:2023, draftPick:43, ppg:7.0,  rpg:3.0, apg:1.0, spg:0.9, bpg:0.5, age:23, height:79 },

  // ── SACRAMENTO KINGS ───────────────────────────────────────────────────────
  { id:"defox",     name:"De'Aaron Fox",           aliases:["de'aaron fox","fox","deaaron fox"],              teamColor:"#5A2D81", team:"Sacramento Kings",        position:"PG", jersey:"5",  draftYear:2017, draftPick:5,  ppg:22.7, rpg:4.0, apg:6.5, spg:1.1, bpg:0.2, age:29, height:75 },
  { id:"sabonis",   name:"Domantas Sabonis",       aliases:["domantas sabonis","sabonis","domas"],            teamColor:"#5A2D81", team:"Sacramento Kings",        position:"C",  jersey:"10", draftYear:2016, draftPick:11, ppg:17.0, rpg:11.5, apg:6.0, spg:1.0, bpg:0.5, age:28, height:83 },
  { id:"kmurray",   name:"Keegan Murray",          aliases:["keegan murray","murray","keegan"],               teamColor:"#5A2D81", team:"Sacramento Kings",        position:"SF", jersey:"13", draftYear:2022, draftPick:4,  ppg:16.0, rpg:4.5, apg:1.5, spg:0.9, bpg:0.5, age:24, height:79 },
  { id:"hbarnes",   name:"Harrison Barnes",        aliases:["harrison barnes","barnes","harrison"],           teamColor:"#5A2D81", team:"Sacramento Kings",        position:"SF", jersey:"40", draftYear:2012, draftPick:7,  ppg:14.0, rpg:5.0, apg:2.0, spg:0.9, bpg:0.5, age:34, height:80 },
  { id:"khuerter",  name:"Kevin Huerter",          aliases:["kevin huerter","huerter","kevin"],               teamColor:"#5A2D81", team:"Sacramento Kings",        position:"SG", jersey:"9",  draftYear:2018, draftPick:19, ppg:12.0, rpg:3.5, apg:3.0, spg:1.0, bpg:0.3, age:28, height:79 },
  { id:"mmonk",     name:"Malik Monk",             aliases:["malik monk","monk","malik"],                     teamColor:"#5A2D81", team:"Sacramento Kings",        position:"SG", jersey:"0",  draftYear:2017, draftPick:11, ppg:13.0, rpg:2.5, apg:3.0, spg:1.0, bpg:0.3, age:29, height:77 },
  { id:"jclarkson", name:"Jordan Clarkson",        aliases:["jordan clarkson","clarkson","jordan"],           teamColor:"#5A2D81", team:"Sacramento Kings",        position:"SG", jersey:"00", draftYear:2014, draftPick:46, ppg:14.0, rpg:3.0, apg:3.0, spg:1.0, bpg:0.3, age:32, height:75 },
  { id:"wkessler",  name:"Walker Kessler",         aliases:["walker kessler","kessler","walker"],             teamColor:"#5A2D81", team:"Sacramento Kings",        position:"C",  jersey:"24", draftYear:2022, draftPick:22, ppg:10.0, rpg:9.0, apg:1.0, spg:0.6, bpg:1.4, age:24, height:85 },
  { id:"kgeorge2",  name:"Keyonte George",         aliases:["keyonte george","george","keyonte"],             teamColor:"#5A2D81", team:"Sacramento Kings",        position:"PG", jersey:"3",  draftYear:2023, draftPick:16, ppg:14.0, rpg:3.0, apg:5.0, spg:1.1, bpg:0.2, age:23, height:77 },

  // ── SAN ANTONIO SPURS ──────────────────────────────────────────────────────
  { id:"wemby",     name:"Victor Wembanyama",      aliases:["victor wembanyama","wembanyama","wemby","victor"], teamColor:"#C4CED4", team:"San Antonio Spurs",     position:"C",  jersey:"1",  draftYear:2023, draftPick:1,  ppg:22.5, rpg:10.6, apg:3.9, spg:1.5, bpg:3.6, age:22, height:88 },
  { id:"dvassell",  name:"Devin Vassell",          aliases:["devin vassell","vassell","devin"],               teamColor:"#C4CED4", team:"San Antonio Spurs",       position:"SG", jersey:"24", draftYear:2020, draftPick:11, ppg:19.0, rpg:4.0, apg:3.0, spg:1.0, bpg:0.3, age:26, height:78 },
  { id:"kjohnson",  name:"Keldon Johnson",         aliases:["keldon johnson","keldon","johnson"],              teamColor:"#C4CED4", team:"San Antonio Spurs",       position:"SF", jersey:"3",  draftYear:2019, draftPick:29, ppg:16.0, rpg:5.0, apg:2.5, spg:0.9, bpg:0.5, age:27, height:79 },
  { id:"jsochan",   name:"Jeremy Sochan",          aliases:["jeremy sochan","sochan","jeremy"],               teamColor:"#C4CED4", team:"San Antonio Spurs",       position:"PF", jersey:"10", draftYear:2022, draftPick:9,  ppg:13.0, rpg:5.5, apg:4.5, spg:0.8, bpg:0.9, age:24, height:80 },
  { id:"scastle",   name:"Stephon Castle",         aliases:["stephon castle","castle","stephon"],             teamColor:"#C4CED4", team:"San Antonio Spurs",       position:"PG", jersey:"4",  draftYear:2024, draftPick:4,  ppg:14.0, rpg:3.5, apg:3.5, spg:1.1, bpg:0.2, age:22, height:77 },
  { id:"tjones",    name:"Tre Jones",              aliases:["tre jones","jones","tre"],                       teamColor:"#C4CED4", team:"San Antonio Spurs",       position:"PG", jersey:"33", draftYear:2020, draftPick:41, ppg:10.0, rpg:3.0, apg:5.0, spg:1.1, bpg:0.2, age:26, height:75 },
  { id:"mbranham",  name:"Malaki Branham",         aliases:["malaki branham","branham","malaki"],             teamColor:"#C4CED4", team:"San Antonio Spurs",       position:"SG", jersey:"5",  draftYear:2022, draftPick:20, ppg:11.0, rpg:3.0, apg:2.0, spg:1.0, bpg:0.3, age:23, height:77 },
  { id:"bwesley",   name:"Blake Wesley",           aliases:["blake wesley","wesley","blake"],                 teamColor:"#C4CED4", team:"San Antonio Spurs",       position:"SG", jersey:"14", draftYear:2022, draftPick:25, ppg:9.0,  rpg:2.5, apg:2.0, spg:1.0, bpg:0.3, age:23, height:78 },
  { id:"cbassey",   name:"Charles Bassey",         aliases:["charles bassey","bassey","charles"],             teamColor:"#C4CED4", team:"San Antonio Spurs",       position:"C",  jersey:"18", draftYear:2021, draftPick:53, ppg:7.5,  rpg:6.5, apg:0.8, spg:0.6, bpg:1.4, age:25, height:83 },

  // ── TORONTO RAPTORS ────────────────────────────────────────────────────────
  { id:"sbarnes",   name:"Scottie Barnes",         aliases:["scottie barnes","barnes","scottie"],             teamColor:"#CE1141", team:"Toronto Raptors",         position:"SF", jersey:"4",  draftYear:2021, draftPick:4,  ppg:20.0, rpg:8.5, apg:5.5, spg:1.2, bpg:0.8, age:24, height:82 },
  { id:"rjbarrett", name:"RJ Barrett",             aliases:["rj barrett","barrett","rj"],                     teamColor:"#CE1141", team:"Toronto Raptors",         position:"SG", jersey:"9",  draftYear:2019, draftPick:3,  ppg:20.0, rpg:5.5, apg:3.5, spg:1.0, bpg:0.4, age:25, height:79 },
  { id:"iquickley", name:"Immanuel Quickley",      aliases:["immanuel quickley","quickley","iq"],             teamColor:"#CE1141", team:"Toronto Raptors",         position:"PG", jersey:"5",  draftYear:2020, draftPick:25, ppg:16.0, rpg:4.0, apg:6.5, spg:1.0, bpg:0.3, age:25, height:76 },
  { id:"jpoeltl",   name:"Jakob Poeltl",           aliases:["jakob poeltl","poeltl","jakob"],                 teamColor:"#CE1141", team:"Toronto Raptors",         position:"C",  jersey:"25", draftYear:2016, draftPick:9,  ppg:11.5, rpg:8.5, apg:3.0, spg:0.7, bpg:1.5, age:30, height:85 },
  { id:"gdick",     name:"Gradey Dick",            aliases:["gradey dick","dick","gradey"],                   teamColor:"#CE1141", team:"Toronto Raptors",         position:"SG", jersey:"1",  draftYear:2023, draftPick:13, ppg:12.0, rpg:3.0, apg:1.5, spg:1.0, bpg:0.3, age:21, height:78 },
  { id:"oagbaji",   name:"Ochai Agbaji",           aliases:["ochai agbaji","agbaji","ochai"],                 teamColor:"#CE1141", team:"Toronto Raptors",         position:"SG", jersey:"14", draftYear:2022, draftPick:14, ppg:11.0, rpg:3.5, apg:1.5, spg:1.0, bpg:0.3, age:24, height:79 },
  { id:"dmitchell2",name:"Davion Mitchell",        aliases:["davion mitchell","davion","dmitchell"],          teamColor:"#CE1141", team:"Toronto Raptors",         position:"PG", jersey:"45", draftYear:2021, draftPick:9,  ppg:11.0, rpg:2.5, apg:4.0, spg:1.1, bpg:0.2, age:25, height:74 },
  { id:"jmogbo",    name:"Jonathan Mogbo",         aliases:["jonathan mogbo","mogbo"],                        teamColor:"#CE1141", team:"Toronto Raptors",         position:"C",  jersey:"17", draftYear:2024, draftPick:43, ppg:7.0,  rpg:5.5, apg:1.0, spg:0.6, bpg:1.4, age:22, height:82 },

  // ── UTAH JAZZ ──────────────────────────────────────────────────────────────
  { id:"lmarkkanen",name:"Lauri Markkanen",        aliases:["lauri markkanen","markkanen","lauri"],           teamColor:"#002B5C", team:"Utah Jazz",               position:"PF", jersey:"23", draftYear:2017, draftPick:7,  ppg:19.0, rpg:8.5, apg:2.0, spg:0.8, bpg:0.8, age:28, height:84 },
  { id:"csexton",   name:"Collin Sexton",          aliases:["collin sexton","sexton","collin","young bull"],  teamColor:"#002B5C", team:"Utah Jazz",               position:"PG", jersey:"2",  draftYear:2018, draftPick:8,  ppg:18.0, rpg:3.0, apg:3.5, spg:1.1, bpg:0.2, age:26, height:74 },
  { id:"jclarkson2",name:"Jordan Clarkson",        aliases:["jordan clarkson","clarkson","jordan c"],         teamColor:"#002B5C", team:"Utah Jazz",               position:"SG", jersey:"00", draftYear:2014, draftPick:46, ppg:14.0, rpg:3.0, apg:3.0, spg:1.0, bpg:0.3, age:33, height:75 },
  { id:"jcollins",  name:"John Collins",           aliases:["john collins","collins","john"],                 teamColor:"#002B5C", team:"Utah Jazz",               position:"PF", jersey:"20", draftYear:2017, draftPick:19, ppg:16.0, rpg:7.0, apg:1.5, spg:0.8, bpg:0.9, age:27, height:80 },
  { id:"wkessler2", name:"Walker Kessler",         aliases:["walker kessler","kessler"],                      teamColor:"#002B5C", team:"Utah Jazz",               position:"C",  jersey:"24", draftYear:2022, draftPick:22, ppg:10.0, rpg:9.0, apg:1.0, spg:0.6, bpg:2.2, age:23, height:85 },
  { id:"kgeorge",   name:"Keyonte George",         aliases:["keyonte george","george"],                       teamColor:"#002B5C", team:"Utah Jazz",               position:"PG", jersey:"3",  draftYear:2023, draftPick:16, ppg:14.0, rpg:3.0, apg:5.0, spg:1.1, bpg:0.2, age:22, height:77 },
  { id:"thendricks",name:"Taylor Hendricks",       aliases:["taylor hendricks","hendricks","taylor"],         teamColor:"#002B5C", team:"Utah Jazz",               position:"PF", jersey:"0",  draftYear:2023, draftPick:9,  ppg:9.0,  rpg:4.5, apg:1.0, spg:0.8, bpg:0.9, age:21, height:82 },
  { id:"icollier",  name:"Isaiah Collier",         aliases:["isaiah collier","collier","isaiah"],             teamColor:"#002B5C", team:"Utah Jazz",               position:"PG", jersey:"23", draftYear:2024, draftPick:29, ppg:8.0,  rpg:2.5, apg:4.0, spg:1.1, bpg:0.2, age:21, height:75 },
  { id:"cwilliams2",name:"Cody Williams",          aliases:["cody williams","cody","cwilliams"],              teamColor:"#002B5C", team:"Utah Jazz",               position:"SF", jersey:"10", draftYear:2024, draftPick:10, ppg:8.0,  rpg:3.5, apg:1.5, spg:0.9, bpg:0.5, age:21, height:81 },

  // ── WASHINGTON WIZARDS ─────────────────────────────────────────────────────
  { id:"kuzma",     name:"Kyle Kuzma",             aliases:["kyle kuzma","kuzma","kuz"],                      teamColor:"#E31837", team:"Washington Wizards",      position:"SF", jersey:"33", draftYear:2017, draftPick:27, ppg:16.5, rpg:6.0, apg:3.0, spg:0.9, bpg:0.5, age:30, height:81 },
  { id:"jpoole",    name:"Jordan Poole",           aliases:["jordan poole","poole","jp"],                     teamColor:"#E31837", team:"Washington Wizards",      position:"SG", jersey:"13", draftYear:2019, draftPick:28, ppg:17.0, rpg:3.0, apg:4.0, spg:1.0, bpg:0.3, age:26, height:76 },
  { id:"bcoulibaly",name:"Bilal Coulibaly",        aliases:["bilal coulibaly","coulibaly","bilal"],           teamColor:"#E31837", team:"Washington Wizards",      position:"SF", jersey:"0",  draftYear:2023, draftPick:7,  ppg:12.0, rpg:4.5, apg:2.5, spg:0.9, bpg:0.5, age:22, height:80 },
  { id:"asarr",     name:"Alexandre Sarr",         aliases:["alexandre sarr","sarr","alex sarr"],             teamColor:"#E31837", team:"Washington Wizards",      position:"C",  jersey:"5",  draftYear:2024, draftPick:2,  ppg:10.0, rpg:6.0, apg:1.5, spg:0.6, bpg:1.4, age:20, height:85 },
  { id:"tyusjones", name:"Tyus Jones",             aliases:["tyus jones","jones","tyus"],                     teamColor:"#E31837", team:"Washington Wizards",      position:"PG", jersey:"5",  draftYear:2015, draftPick:24, ppg:11.0, rpg:2.5, apg:6.5, spg:1.1, bpg:0.2, age:30, height:73 },
  { id:"ckispert",  name:"Corey Kispert",          aliases:["corey kispert","kispert","corey"],               teamColor:"#E31837", team:"Washington Wizards",      position:"SF", jersey:"24", draftYear:2021, draftPick:15, ppg:12.0, rpg:3.5, apg:1.5, spg:0.9, bpg:0.5, age:25, height:79 },
  { id:"jdavis2",   name:"Johnny Davis",           aliases:["johnny davis","johnny","jdavis"],                teamColor:"#E31837", team:"Washington Wizards",      position:"SG", jersey:"6",  draftYear:2022, draftPick:10, ppg:7.0,  rpg:2.5, apg:1.5, spg:1.0, bpg:0.3, age:23, height:79 },
  { id:"zrisacher", name:"Zaccharie Risacher",     aliases:["zaccharie risacher","risacher","zaccharie"],    teamColor:"#E31837", team:"Washington Wizards",      position:"SF", jersey:"10", draftYear:2024, draftPick:1,  ppg:8.5,  rpg:3.5, apg:1.0, spg:0.9, bpg:0.5, age:20, height:81 },
  { id:"mbagley",   name:"Marvin Bagley III",      aliases:["marvin bagley iii","bagley","marvin bagley"],    teamColor:"#E31837", team:"Washington Wizards",      position:"PF", jersey:"35", draftYear:2018, draftPick:2,  ppg:13.5, rpg:7.5, apg:1.0, spg:0.8, bpg:0.9, age:27, height:82 },
];

// Export all current player names for autocomplete
export const CURRENT_NBA_PLAYER_NAMES: string[] = CURRENT_NBA_PLAYERS.map(p => p.name);
