import type { Player, Trio } from "./playerData";

const CURRENT_PLAYERS: Record<string, Player> = {
  jokic: {
    id: "jokic_c",
    name: "Nikola Jokic",
    team: "Denver Nuggets",
    position: "C",
    jersey: "15",
    teamColor: "#FEC524",
    stats: { ppg: 26.4, rpg: 12.4, apg: 9.0 },
    accolades: ["1x Champion", "3x MVP", "1x Finals MVP"],
    era: "2015–present",
  },
  embiid: {
    id: "embiid_c",
    name: "Joel Embiid",
    team: "Philadelphia 76ers",
    position: "C",
    jersey: "21",
    teamColor: "#006BB6",
    stats: { ppg: 27.5, rpg: 11.2, apg: 3.7 },
    accolades: ["1x MVP", "1x scoring title", "7x All-Star"],
    era: "2016–present",
  },
  giannis: {
    id: "giannis_c",
    name: "Giannis Antetokounmpo",
    team: "Milwaukee Bucks",
    position: "PF",
    jersey: "34",
    teamColor: "#00471B",
    stats: { ppg: 29.2, rpg: 11.7, apg: 5.8 },
    accolades: ["1x Champion", "2x MVP", "1x DPOY"],
    era: "2013–present",
  },
  wemby: {
    id: "wemby",
    name: "Victor Wembanyama",
    team: "San Antonio Spurs",
    position: "C",
    jersey: "1",
    teamColor: "#C4CED4",
    stats: { ppg: 22.5, rpg: 10.6, apg: 3.9 },
    accolades: ["1x ROY", "2x All-Star", "1x blocks title"],
    era: "2023–present",
  },
  curry: {
    id: "curry_c",
    name: "Stephen Curry",
    team: "Golden State Warriors",
    position: "PG",
    jersey: "30",
    teamColor: "#1D428A",
    stats: { ppg: 24.8, rpg: 4.6, apg: 6.4 },
    accolades: ["4x Champion", "2x MVP", "All-time 3PT leader"],
    era: "2009–present",
  },
  luka: {
    id: "luka_c",
    name: "Luka Doncic",
    team: "Los Angeles Lakers",
    position: "PG",
    jersey: "77",
    teamColor: "#552583",
    stats: { ppg: 28.7, rpg: 8.7, apg: 8.3 },
    accolades: ["1x Rookie of the Year", "5x All-NBA 1st Team", "1x All-Star MVP"],
    era: "2018–present",
  },
  sga: {
    id: "sga",
    name: "Shai Gilgeous-Alexander",
    team: "Oklahoma City Thunder",
    position: "SG",
    jersey: "2",
    teamColor: "#007AC1",
    stats: { ppg: 24.5, rpg: 4.6, apg: 5.9 },
    accolades: ["1x scoring title", "5x All-Star", "2x All-NBA 1st Team"],
    era: "2018–present",
  },
  durant: {
    id: "durant_c",
    name: "Kevin Durant",
    team: "Phoenix Suns",
    position: "SF",
    jersey: "35",
    teamColor: "#1D1160",
    stats: { ppg: 27.3, rpg: 7.0, apg: 4.4 },
    accolades: ["2x Champion", "2x Finals MVP", "1x MVP"],
    era: "2007–present",
  },
  tatum: {
    id: "tatum_c",
    name: "Jayson Tatum",
    team: "Boston Celtics",
    position: "SF",
    jersey: "0",
    teamColor: "#007A33",
    stats: { ppg: 26.9, rpg: 8.1, apg: 4.9 },
    accolades: ["1x Champion", "1x Finals MVP", "6x All-Star"],
    era: "2017–present",
  },
  kawhi: {
    id: "kawhi",
    name: "Kawhi Leonard",
    team: "Los Angeles Clippers",
    position: "SF",
    jersey: "2",
    teamColor: "#C8102E",
    stats: { ppg: 19.7, rpg: 6.5, apg: 3.6 },
    accolades: ["2x Champion", "2x Finals MVP", "2x DPOY"],
    era: "2011–present",
  },
  lebron: {
    id: "lebron_c",
    name: "LeBron James",
    team: "Los Angeles Lakers",
    position: "SF",
    jersey: "23",
    teamColor: "#552583",
    stats: { ppg: 27.2, rpg: 7.5, apg: 7.4 },
    accolades: ["4x Champion", "4x MVP", "All-time scoring leader"],
    era: "2003–present",
  },
  ad: {
    id: "ad",
    name: "Anthony Davis",
    team: "Los Angeles Lakers",
    position: "C/PF",
    jersey: "3",
    teamColor: "#552583",
    stats: { ppg: 23.8, rpg: 10.3, apg: 2.7 },
    accolades: ["1x Champion", "8x All-Star", "1x All-Star Game MVP"],
    era: "2012–present",
  },
  booker: {
    id: "booker_c",
    name: "Devin Booker",
    team: "Phoenix Suns",
    position: "SG",
    jersey: "1",
    teamColor: "#1D1160",
    stats: { ppg: 23.5, rpg: 4.5, apg: 4.7 },
    accolades: ["1x scoring title", "5x All-Star", "1x Olympic gold"],
    era: "2015–present",
  },
  ant: {
    id: "ant",
    name: "Anthony Edwards",
    team: "Minnesota Timberwolves",
    position: "SG",
    jersey: "5",
    teamColor: "#236192",
    stats: { ppg: 24.6, rpg: 5.4, apg: 4.9 },
    accolades: ["3x All-Star", "1x All-NBA 1st Team"],
    era: "2020–present",
  },
  ja: {
    id: "ja",
    name: "Ja Morant",
    team: "Memphis Grizzlies",
    position: "PG",
    jersey: "12",
    teamColor: "#5D76A9",
    stats: { ppg: 22.7, rpg: 5.6, apg: 7.9 },
    accolades: ["1x ROY", "1x Most Improved", "2x All-Star"],
    era: "2019–present",
  },
  trae: {
    id: "trae",
    name: "Trae Young",
    team: "Atlanta Hawks",
    position: "PG",
    jersey: "11",
    teamColor: "#E03A3E",
    stats: { ppg: 26.2, rpg: 3.9, apg: 10.8 },
    accolades: ["1x scoring title", "3x All-Star", "1x All-NBA 2nd Team"],
    era: "2018–present",
  },
  dame: {
    id: "dame_c",
    name: "Damian Lillard",
    team: "Milwaukee Bucks",
    position: "PG",
    jersey: "0",
    teamColor: "#00471B",
    stats: { ppg: 24.7, rpg: 4.2, apg: 6.9 },
    accolades: ["1x scoring title", "7x All-Star", "1x Olympic gold"],
    era: "2012–present",
  },
  brunson: {
    id: "brunson",
    name: "Jalen Brunson",
    team: "New York Knicks",
    position: "PG",
    jersey: "11",
    teamColor: "#F58426",
    stats: { ppg: 22.1, rpg: 3.3, apg: 6.2 },
    accolades: ["3x All-Star", "1x All-NBA 2nd Team"],
    era: "2018–present",
  },
  kat: {
    id: "kat",
    name: "Karl-Anthony Towns",
    team: "New York Knicks",
    position: "C",
    jersey: "32",
    teamColor: "#F58426",
    stats: { ppg: 22.7, rpg: 10.8, apg: 3.2 },
    accolades: ["1x ROY", "3x All-Star", "1x 3PT contest winner"],
    era: "2015–present",
  },
  bam: {
    id: "bam",
    name: "Bam Adebayo",
    team: "Miami Heat",
    position: "C",
    jersey: "13",
    teamColor: "#98002E",
    stats: { ppg: 19.2, rpg: 10.0, apg: 3.8 },
    accolades: ["4x All-Star", "1x All-Defensive 1st Team"],
    era: "2017–present",
  },
  banchero: {
    id: "banchero",
    name: "Paolo Banchero",
    team: "Orlando Magic",
    position: "PF",
    jersey: "5",
    teamColor: "#0077C0",
    stats: { ppg: 22.6, rpg: 6.9, apg: 4.7 },
    accolades: ["1x ROY", "2x All-Star"],
    era: "2022–present",
  },
};

export const CURRENT_TRIOS: Trio[] = [
  {
    id: "current-bigs",
    category: "Center of the Universe",
    description: "Who is the most dominant big man in today's NBA?",
    players: [CURRENT_PLAYERS.jokic, CURRENT_PLAYERS.embiid, CURRENT_PLAYERS.wemby],
  },
  {
    id: "current-guards",
    category: "Guard Excellence",
    description: "The three most electric ball-handlers in the league right now",
    players: [CURRENT_PLAYERS.curry, CURRENT_PLAYERS.luka, CURRENT_PLAYERS.sga],
  },
  {
    id: "current-wings",
    category: "Championship Wings",
    description: "Proven winners who can take over any game",
    players: [CURRENT_PLAYERS.durant, CURRENT_PLAYERS.tatum, CURRENT_PLAYERS.kawhi],
  },
  {
    id: "current-lakers",
    category: "Laker Royalty",
    description: "The Lakers' star trio — who's the real alpha?",
    players: [CURRENT_PLAYERS.lebron, CURRENT_PLAYERS.ad, CURRENT_PLAYERS.luka],
  },
  {
    id: "current-young-guns",
    category: "Next Generation",
    description: "The young stars poised to take over the NBA",
    players: [CURRENT_PLAYERS.ant, CURRENT_PLAYERS.wemby, CURRENT_PLAYERS.banchero],
  },
  {
    id: "current-playmakers",
    category: "Passing & Scoring PGs",
    description: "Point guards who do it all with flair",
    players: [CURRENT_PLAYERS.trae, CURRENT_PLAYERS.ja, CURRENT_PLAYERS.brunson],
  },
  {
    id: "current-scorers",
    category: "Elite Scorers",
    description: "Three of the most unstoppable offensive players alive",
    players: [CURRENT_PLAYERS.giannis, CURRENT_PLAYERS.embiid, CURRENT_PLAYERS.booker],
  },
  {
    id: "current-franchise",
    category: "Franchise Cornerstones",
    description: "Stars who define their entire franchises",
    players: [CURRENT_PLAYERS.tatum, CURRENT_PLAYERS.dame, CURRENT_PLAYERS.kat],
  },
];
