import type { StatLinePlayer } from "./statLineData";

export const CURRENT_STAT_LINE_PLAYERS: StatLinePlayer[] = [
  {
    id: "jokic_c",
    name: "Nikola Jokic",
    aliases: ["nikola jokic", "jokic", "the joker", "nikola"],
    teamColor: "#FEC524",
    team: "Denver Nuggets",
    position: "C",
    jersey: "15",
    era: "2015–present",
    stats: { ppg: 27.7, rpg: 12.9, apg: 10.7, spg: 1.4, bpg: 0.8, fgPct: 56.9, threePct: 38.0 },
  },
  {
    id: "giannis_c",
    name: "Giannis Antetokounmpo",
    aliases: ["giannis antetokounmpo", "giannis", "greek freak", "the greek freak"],
    teamColor: "#00471B",
    team: "Milwaukee Bucks",
    position: "PF",
    jersey: "34",
    era: "2013–present",
    stats: { ppg: 27.6, rpg: 9.8, apg: 5.4, spg: 1.0, bpg: 0.6, fgPct: 55.4, threePct: 28.3 },
  },
  {
    id: "luka_c",
    name: "Luka Doncic",
    aliases: ["luka doncic", "luka", "doncic", "luka magic"],
    teamColor: "#552583",
    team: "Los Angeles Lakers",
    position: "PG",
    jersey: "77",
    era: "2018–present",
    stats: { ppg: 33.5, rpg: 7.7, apg: 8.3, spg: 1.6, bpg: 0.5, fgPct: 47.6, threePct: 36.6 },
  },
  {
    id: "sga",
    name: "Shai Gilgeous-Alexander",
    aliases: ["shai gilgeous-alexander", "sga", "shai", "gilgeous-alexander"],
    teamColor: "#007AC1",
    team: "Oklahoma City Thunder",
    position: "SG",
    jersey: "2",
    era: "2018–present",
    stats: { ppg: 31.1, rpg: 4.3, apg: 6.6, spg: 1.4, bpg: 0.8, fgPct: 55.3, threePct: 38.6 },
  },
  {
    id: "tatum_c",
    name: "Jayson Tatum",
    aliases: ["jayson tatum", "tatum", "jt"],
    teamColor: "#007A33",
    team: "Boston Celtics",
    position: "SF",
    jersey: "0",
    era: "2017–present",
    stats: { ppg: 21.8, rpg: 10.0, apg: 5.3, spg: 1.4, bpg: 0.6, fgPct: 46.1, threePct: 37.2 },
  },
  {
    id: "embiid_c",
    name: "Joel Embiid",
    aliases: ["joel embiid", "embiid", "the process", "jo"],
    teamColor: "#006BB6",
    team: "Philadelphia 76ers",
    position: "C",
    jersey: "21",
    era: "2016–present",
    stats: { ppg: 26.9, rpg: 7.7, apg: 4.0, spg: 1.0, bpg: 1.3, fgPct: 52.5, threePct: 35.0 },
  },
  {
    id: "curry_c",
    name: "Stephen Curry",
    aliases: ["stephen curry", "steph curry", "curry", "steph", "chef curry"],
    teamColor: "#1D428A",
    team: "Golden State Warriors",
    position: "PG",
    jersey: "30",
    era: "2009–present",
    stats: { ppg: 26.6, rpg: 3.6, apg: 4.7, spg: 1.1, bpg: 0.3, fgPct: 47.3, threePct: 42.8 },
  },
  {
    id: "durant_c",
    name: "Kevin Durant",
    aliases: ["kevin durant", "durant", "kd", "slim reaper"],
    teamColor: "#CE1141",
    team: "Houston Rockets",
    position: "SF",
    jersey: "35",
    era: "2007–present",
    stats: { ppg: 26.0, rpg: 5.5, apg: 4.8, spg: 0.8, bpg: 0.9, fgPct: 52.0, threePct: 41.3 },
  },
  {
    id: "lebron_c",
    name: "LeBron James",
    aliases: ["lebron james", "lebron", "king james", "the king"],
    teamColor: "#552583",
    team: "Los Angeles Lakers",
    position: "SF",
    jersey: "23",
    era: "2003–present",
    stats: { ppg: 20.9, rpg: 6.1, apg: 7.2, spg: 1.2, bpg: 0.6, fgPct: 51.5, threePct: 31.7 },
  },
  {
    id: "ad_c",
    name: "Anthony Davis",
    aliases: ["anthony davis", "ad", "the brow", "davis"],
    teamColor: "#E31837",
    team: "Washington Wizards",
    position: "C/PF",
    jersey: "3",
    era: "2012–present",
    stats: { ppg: 20.4, rpg: 11.1, apg: 2.8, spg: 1.1, bpg: 1.7, fgPct: 53.0, threePct: 24.5 },
  },
  {
    id: "ant_c",
    name: "Anthony Edwards",
    aliases: ["anthony edwards", "ant", "ant man", "edwards"],
    teamColor: "#236192",
    team: "Minnesota Timberwolves",
    position: "SG",
    jersey: "5",
    era: "2020–present",
    stats: { ppg: 28.8, rpg: 5.0, apg: 3.7, spg: 1.4, bpg: 0.8, fgPct: 48.9, threePct: 39.9 },
  },
  {
    id: "wemby_c",
    name: "Victor Wembanyama",
    aliases: ["victor wembanyama", "wembanyama", "wemby", "victor"],
    teamColor: "#C4CED4",
    team: "San Antonio Spurs",
    position: "C",
    jersey: "1",
    era: "2023–present",
    stats: { ppg: 25.0, rpg: 11.5, apg: 3.1, spg: 0.9, bpg: 3.1, fgPct: 51.1, threePct: 34.9 },
  },
  {
    id: "trae_c",
    name: "Trae Young",
    aliases: ["trae young", "trae", "ice trae", "young"],
    teamColor: "#E31837",
    team: "Washington Wizards",
    position: "PG",
    jersey: "11",
    era: "2018–present",
    stats: { ppg: 22.0, rpg: 4.0, apg: 10.0, spg: 1.0, bpg: 0.1, fgPct: 44.0, threePct: 35.5 },
  },
  {
    id: "ja_c",
    name: "Ja Morant",
    aliases: ["ja morant", "ja", "morant"],
    teamColor: "#5D76A9",
    team: "Memphis Grizzlies",
    position: "PG",
    jersey: "12",
    era: "2019–present",
    stats: { ppg: 19.5, rpg: 3.3, apg: 8.1, spg: 1.2, bpg: 0.3, fgPct: 47.4, threePct: 32.5 },
  },
  {
    id: "booker_c",
    name: "Devin Booker",
    aliases: ["devin booker", "booker", "book", "dbook"],
    teamColor: "#1D1160",
    team: "Phoenix Suns",
    position: "SG",
    jersey: "1",
    era: "2015–present",
    stats: { ppg: 26.1, rpg: 3.6, apg: 6.8, spg: 0.8, bpg: 0.3, fgPct: 46.7, threePct: 36.9 },
  },
  {
    id: "dame_c",
    name: "Damian Lillard",
    aliases: ["damian lillard", "dame", "lillard", "dame dolla"],
    teamColor: "#E03A3E",
    team: "Portland Trail Blazers",
    position: "PG",
    jersey: "0",
    era: "2012–present",
    stats: { ppg: 24.7, rpg: 4.2, apg: 6.9, spg: 1.0, bpg: 0.3, fgPct: 43.7, threePct: 37.1 },
  },
  {
    id: "kawhi_c",
    name: "Kawhi Leonard",
    aliases: ["kawhi leonard", "kawhi", "the klaw", "leonard"],
    teamColor: "#C8102E",
    team: "Los Angeles Clippers",
    position: "SF",
    jersey: "2",
    era: "2011–present",
    stats: { ppg: 27.9, rpg: 6.4, apg: 3.6, spg: 1.8, bpg: 0.8, fgPct: 50.5, threePct: 38.7 },
  },
  {
    id: "bam_c",
    name: "Bam Adebayo",
    aliases: ["bam adebayo", "bam", "adebayo"],
    teamColor: "#98002E",
    team: "Miami Heat",
    position: "C",
    jersey: "13",
    era: "2017–present",
    stats: { ppg: 20.1, rpg: 10.0, apg: 3.2, spg: 1.2, bpg: 0.7, fgPct: 44.2, threePct: 31.8 },
  },
];
