export interface GuessWhoPlayer {
  id: string;
  name: string;
  aliases: string[]; // accepted answers (first name, last name, full name, nickname)
  teamColor: string;
  team: string;
  position: string;
  jersey: string;
  clues: [string, string, string, string, string]; // 5 clues, vague → specific
}

export const GUESS_WHO_PLAYERS: GuessWhoPlayer[] = [
  {
    id: "jordan",
    name: "Michael Jordan",
    aliases: ["michael jordan", "jordan", "mj", "mike"],
    teamColor: "#CE1141",
    team: "Chicago Bulls",
    position: "SG",
    jersey: "23",
    clues: [
      "A shooting guard who dominated the late 80s and 90s and is considered by many the greatest ever.",
      "Never lost in the NBA Finals — went a perfect 6 for 6.",
      "Led the league in scoring 10 times over their career.",
      "Played for a Midwest franchise, wearing #23.",
      "Starred alongside Bugs Bunny in a famous 1996 movie.",
    ],
  },
  {
    id: "lebron",
    name: "LeBron James",
    aliases: ["lebron james", "lebron", "king james", "the king"],
    teamColor: "#552583",
    team: "Los Angeles Lakers",
    position: "SF",
    jersey: "23",
    clues: [
      "An active player often cited as the greatest of all time, with a career spanning 20+ years.",
      "Has played for 3 different NBA franchises.",
      "4x NBA Champion and 4x MVP.",
      "Was the #1 overall draft pick straight out of high school in 2003.",
      "Known as 'The King' and grew up in Akron, Ohio.",
    ],
  },
  {
    id: "kobe",
    name: "Kobe Bryant",
    aliases: ["kobe bryant", "kobe", "black mamba", "mamba"],
    teamColor: "#552583",
    team: "Los Angeles Lakers",
    position: "SG",
    jersey: "24",
    clues: [
      "A shooting guard who spent their entire 20-year career with one franchise.",
      "Won 5 NBA championships, all with the same team.",
      "Scored 81 points in a single game — the 2nd highest total in NBA history.",
      "Named an All-Star 18 times.",
      "Known as the 'Black Mamba'.",
    ],
  },
  {
    id: "curry",
    name: "Stephen Curry",
    aliases: ["stephen curry", "steph curry", "curry", "steph", "chef curry"],
    teamColor: "#1D428A",
    team: "Golden State Warriors",
    position: "PG",
    jersey: "30",
    clues: [
      "A point guard widely credited with revolutionizing the modern NBA through long-range shooting.",
      "4x NBA Champion with the same franchise.",
      "Holds the all-time record for 3-pointers made.",
      "The first unanimous MVP in NBA history.",
      "Son of former NBA player Dell Curry.",
    ],
  },
  {
    id: "shaq",
    name: "Shaquille O'Neal",
    aliases: ["shaquille o'neal", "shaq", "shaquille", "the diesel", "big aristotle"],
    teamColor: "#552583",
    team: "Los Angeles Lakers",
    position: "C",
    jersey: "34",
    clues: [
      "A 7'1\" center who was nearly unstoppable in the paint during the late 90s and 2000s.",
      "Won 4 NBA championships with 2 different teams.",
      "Named Finals MVP 3 times.",
      "Career scoring average of 23.7 points per game over 19 seasons.",
      "Known as 'The Diesel' and recorded multiple rap albums.",
    ],
  },
  {
    id: "timD",
    name: "Tim Duncan",
    aliases: ["tim duncan", "duncan", "timmy", "the big fundamental"],
    teamColor: "#C4CED4",
    team: "San Antonio Spurs",
    position: "PF",
    jersey: "21",
    clues: [
      "A power forward/center known for textbook-perfect fundamental play.",
      "Won 5 championships, all with the same small-market franchise.",
      "Career spanned 19 seasons, all with one team.",
      "Nicknamed 'The Big Fundamental'.",
      "Was drafted #1 overall out of Wake Forest in 1997.",
    ],
  },
  {
    id: "magic",
    name: "Magic Johnson",
    aliases: ["magic johnson", "magic", "earvin johnson", "earvin"],
    teamColor: "#552583",
    team: "Los Angeles Lakers",
    position: "PG",
    jersey: "32",
    clues: [
      "A point guard from the Showtime era who made the fast break an art form.",
      "Won 5 NBA championships in the 1980s.",
      "Career assists average of 11.2 per game — among the highest ever.",
      "Wore #32 their entire career with one franchise.",
      "Famous rivalry with Larry Bird began in the 1979 NCAA Championship.",
    ],
  },
  {
    id: "kareem",
    name: "Kareem Abdul-Jabbar",
    aliases: ["kareem abdul-jabbar", "kareem", "kareem abdul jabbar", "lew alcindor"],
    teamColor: "#552583",
    team: "Los Angeles Lakers",
    position: "C",
    jersey: "33",
    clues: [
      "A center who played from 1969 to 1989, spanning two very different eras of basketball.",
      "Won 6 NBA championships.",
      "Won the MVP award 6 times — more than any player in NBA history.",
      "Famous for an unstoppable shot called the 'skyhook'.",
      "Was the NBA's all-time leading scorer for 38 years.",
    ],
  },
  {
    id: "wilt",
    name: "Wilt Chamberlain",
    aliases: ["wilt chamberlain", "wilt", "the stilt", "wilt the stilt", "big dipper"],
    teamColor: "#552583",
    team: "Los Angeles Lakers",
    position: "C",
    jersey: "13",
    clues: [
      "A dominant center from the 1960s who put up statistics that still seem impossible today.",
      "Averaged 50.4 points per game in a single season — a record that may never be broken.",
      "Scored 100 points in a single game.",
      "Career rebounding average of 22.9 per game.",
      "Remarkably, never fouled out of a single game in their entire career.",
    ],
  },
  {
    id: "dirk",
    name: "Dirk Nowitzki",
    aliases: ["dirk nowitzki", "dirk", "nowitzki", "the german wunderkind"],
    teamColor: "#00538C",
    team: "Dallas Mavericks",
    position: "PF",
    jersey: "41",
    clues: [
      "A European player who redefined what was expected of big men in the NBA.",
      "Spent their entire 21-season career with one franchise in Texas.",
      "Famous for a unique one-legged fadeaway jump shot.",
      "Won the 2011 NBA championship and was named Finals MVP.",
      "The first European-born player to win the NBA MVP award.",
    ],
  },
  {
    id: "giannis",
    name: "Giannis Antetokounmpo",
    aliases: ["giannis antetokounmpo", "giannis", "greek freak", "the greek freak"],
    teamColor: "#00471B",
    team: "Milwaukee Bucks",
    position: "PF",
    jersey: "34",
    clues: [
      "A player who came from Greece and was selected 15th overall in the 2013 NBA Draft.",
      "Stands 6'11\" and is known for explosive, unguardable drives to the basket.",
      "Won the MVP award twice.",
      "Led their team to the 2021 NBA championship and was named Finals MVP.",
      "Nicknamed 'The Greek Freak'.",
    ],
  },
  {
    id: "hakeem",
    name: "Hakeem Olajuwon",
    aliases: ["hakeem olajuwon", "hakeem", "olajuwon", "the dream", "akeem"],
    teamColor: "#CE1141",
    team: "Houston Rockets",
    position: "C",
    jersey: "34",
    clues: [
      "A center born in Lagos, Nigeria who became one of the most skilled big men ever.",
      "Won 2 back-to-back NBA championships in 1994 and 1995.",
      "Named Finals MVP both years.",
      "Known for an elusive series of post moves called the 'Dream Shake'.",
      "Also won a gold medal with Team USA at the 1996 Olympics.",
    ],
  },
  {
    id: "jokic",
    name: "Nikola Jokic",
    aliases: ["nikola jokic", "jokic", "the joker", "nikola"],
    teamColor: "#FEC524",
    team: "Denver Nuggets",
    position: "C",
    jersey: "15",
    clues: [
      "A center from Serbia selected 41st overall in the 2014 draft — one of the greatest steals in draft history.",
      "Revolutionized the center position with elite passing and playmaking.",
      "Won the MVP award 3 times.",
      "Led their team to the 2023 NBA championship as Finals MVP.",
      "Nicknamed 'The Joker' and is known to be passionate about horses.",
    ],
  },
  {
    id: "bird",
    name: "Larry Bird",
    aliases: ["larry bird", "bird", "larry legend", "the hick from french lick"],
    teamColor: "#007A33",
    team: "Boston Celtics",
    position: "SF",
    jersey: "33",
    clues: [
      "A small forward from the 1980s known for elite shooting, passing, and trash talk.",
      "Won 3 NBA championships.",
      "Won the MVP award 3 consecutive times from 1984 to 1986.",
      "Wore #33 for a storied Boston franchise.",
      "Famous rivalry with Magic Johnson is considered one of the greatest in sports history.",
    ],
  },
  {
    id: "russell",
    name: "Bill Russell",
    aliases: ["bill russell", "russell", "william russell"],
    teamColor: "#007A33",
    team: "Boston Celtics",
    position: "C",
    jersey: "6",
    clues: [
      "A center from the late 1950s and 60s who is the most decorated champion in NBA history.",
      "Won 11 NBA championships in 13 seasons.",
      "Won the MVP award 5 times.",
      "Known more for defense and rebounding than scoring — averaged 22.5 rebounds per game.",
      "Became the first Black head coach in major American professional sports in 1966.",
    ],
  },
];
