export type HLPlayer = {
  name: string;
  value: number;
  hint: string;
};

export type HLCategory = {
  id: string;
  label: string;
  description: string;
  unit: string;
  format: "decimal1" | "integer";
  players: HLPlayer[];
};

export const HL_CATEGORIES: HLCategory[] = [
  {
    id: "ppg",
    label: "Career PPG",
    description: "Career Points Per Game average",
    unit: "PPG",
    format: "decimal1",
    players: [
      { name: "Michael Jordan",       value: 30.1, hint: "6× NBA Champion · 6× Finals MVP" },
      { name: "Elgin Baylor",          value: 27.4, hint: "11× All-Star · Never won a ring" },
      { name: "Kevin Durant",          value: 27.3, hint: "2× NBA Champion · 2× Finals MVP" },
      { name: "LeBron James",          value: 27.1, hint: "4× NBA Champion · All-Time Scoring Leader" },
      { name: "Jerry West",            value: 27.0, hint: "NBA Champion 1972 · Logo inspiration" },
      { name: "Allen Iverson",         value: 26.7, hint: "2001 MVP · 11× All-Star" },
      { name: "Bob Pettit",            value: 26.4, hint: "2× MVP · 1958 NBA Champion" },
      { name: "Oscar Robertson",       value: 25.7, hint: "1971 NBA Champion · Triple-double king" },
      { name: "Kobe Bryant",           value: 25.0, hint: "5× NBA Champion · 81 points in 2006" },
      { name: "Stephen Curry",         value: 24.8, hint: "4× NBA Champion · 3-point record holder" },
      { name: "Dominique Wilkins",     value: 24.8, hint: "9× All-Star · Dunk Contest legend" },
      { name: "Kareem Abdul-Jabbar",   value: 24.6, hint: "6× NBA Champion · 6× MVP" },
      { name: "Larry Bird",            value: 24.3, hint: "3× NBA Champion · 3× MVP" },
      { name: "Shaquille O'Neal",      value: 23.7, hint: "4× NBA Champion · 3× Finals MVP" },
      { name: "Carmelo Anthony",       value: 22.5, hint: "10× All-Star · Olympic gold medalist" },
      { name: "Charles Barkley",       value: 22.1, hint: "1993 MVP · Never won a ring" },
      { name: "Dwyane Wade",           value: 22.0, hint: "3× NBA Champion · 2006 Finals MVP" },
      { name: "Patrick Ewing",         value: 21.0, hint: "11× All-Star · Never won a ring" },
      { name: "Dirk Nowitzki",         value: 20.7, hint: "2011 NBA Champion · 2011 Finals MVP" },
      { name: "Paul Pierce",           value: 19.7, hint: "2008 NBA Champion · 2008 Finals MVP" },
      { name: "Magic Johnson",         value: 19.5, hint: "5× NBA Champion · 3× Finals MVP" },
      { name: "Tim Duncan",            value: 19.0, hint: "5× NBA Champion · 3× Finals MVP" },
      { name: "Reggie Miller",         value: 18.2, hint: "5× All-Star · Never won a ring" },
    ],
  },
  {
    id: "rpg",
    label: "Career RPG",
    description: "Career Rebounds Per Game average",
    unit: "RPG",
    format: "decimal1",
    players: [
      { name: "Wilt Chamberlain",      value: 22.9, hint: "4× MVP · 2× NBA Champion" },
      { name: "Bill Russell",          value: 22.5, hint: "11× NBA Champion · 5× MVP" },
      { name: "Bob Pettit",            value: 16.2, hint: "2× MVP · 1958 NBA Champion" },
      { name: "Elvin Hayes",           value: 13.4, hint: "1978 NBA Champion · 12× All-Star" },
      { name: "Nikola Jokic",          value: 11.8, hint: "3× MVP · 2023 NBA Champion" },
      { name: "Dennis Rodman",         value: 13.1, hint: "5× NBA Champion · 7× rebounding titles" },
      { name: "Dwight Howard",         value: 12.5, hint: "3× DPOY · 2009 Dunk Contest champ" },
      { name: "Moses Malone",          value: 12.2, hint: "1983 NBA Champion · 3× MVP" },
      { name: "Charles Barkley",       value: 11.7, hint: "1993 MVP · 11× All-Star" },
      { name: "Kareem Abdul-Jabbar",   value: 11.2, hint: "6× NBA Champion · All-Time #2 scorer" },
      { name: "Hakeem Olajuwon",       value: 11.1, hint: "2× NBA Champion · 1994 Finals MVP" },
      { name: "Shaquille O'Neal",      value: 10.9, hint: "4× NBA Champion · 3× Finals MVP" },
      { name: "Tim Duncan",            value: 10.8, hint: "5× NBA Champion · 3× Finals MVP" },
      { name: "Anthony Davis",         value: 10.7, hint: "2020 NBA Champion · 8× All-Star" },
      { name: "Kevin Garnett",         value: 10.0, hint: "2008 NBA Champion · 2004 MVP" },
      { name: "Patrick Ewing",         value:  9.8, hint: "11× All-Star · Never won a ring" },
      { name: "Michael Jordan",        value:  6.2, hint: "6× NBA Champion · 6× Finals MVP" },
      { name: "LeBron James",          value:  7.5, hint: "4× NBA Champion · All-Time scoring leader" },
      { name: "Kobe Bryant",           value:  5.4, hint: "5× NBA Champion · 81 points in 2006" },
      { name: "Allen Iverson",         value:  3.7, hint: "2001 MVP · 11× All-Star" },
    ],
  },
  {
    id: "apg",
    label: "Career APG",
    description: "Career Assists Per Game average",
    unit: "APG",
    format: "decimal1",
    players: [
      { name: "Magic Johnson",         value: 11.2, hint: "5× NBA Champion · 3× MVP" },
      { name: "John Stockton",         value: 10.5, hint: "All-time assists & steals leader" },
      { name: "Oscar Robertson",       value:  9.5, hint: "1971 NBA Champion · 1962 MVP" },
      { name: "Chris Paul",            value:  9.4, hint: "4× assists title · 12× All-Star" },
      { name: "Isiah Thomas",          value:  9.3, hint: "2× NBA Champion · 1990 Finals MVP" },
      { name: "Steve Nash",            value:  8.5, hint: "2× MVP · 8× All-Star" },
      { name: "Jason Kidd",            value:  8.7, hint: "2011 NBA Champion · 10× All-Star" },
      { name: "Russell Westbrook",     value:  8.4, hint: "2017 MVP · Triple-double season record" },
      { name: "Mark Jackson",          value:  8.0, hint: "3rd all-time in assists (career total)" },
      { name: "Rajon Rondo",           value:  7.7, hint: "2008 NBA Champion · 4× assists title" },
      { name: "LeBron James",          value:  7.4, hint: "4× NBA Champion · All-Time scoring leader" },
      { name: "Gary Payton",           value:  6.7, hint: "1996 DPOY · 9× All-Defensive First Team" },
      { name: "Allen Iverson",         value:  6.2, hint: "2001 MVP · 11× All-Star" },
      { name: "Dwyane Wade",           value:  5.4, hint: "3× NBA Champion · 2006 Finals MVP" },
      { name: "Michael Jordan",        value:  5.3, hint: "6× NBA Champion · 6× Finals MVP" },
      { name: "Kobe Bryant",           value:  4.7, hint: "5× NBA Champion · 81 points in 2006" },
      { name: "Tim Duncan",            value:  3.0, hint: "5× NBA Champion · 3× Finals MVP" },
      { name: "Shaquille O'Neal",      value:  2.3, hint: "4× NBA Champion · 3× Finals MVP" },
    ],
  },
  {
    id: "allstar",
    label: "All-Star Appearances",
    description: "Career NBA All-Star Game selections",
    unit: "selections",
    format: "integer",
    players: [
      { name: "LeBron James",          value: 20, hint: "4× NBA Champion · All-Time scoring leader" },
      { name: "Kareem Abdul-Jabbar",   value: 19, hint: "6× NBA Champion · 6× MVP" },
      { name: "Kobe Bryant",           value: 18, hint: "5× NBA Champion · 81 points in 2006" },
      { name: "Shaquille O'Neal",      value: 15, hint: "4× NBA Champion · 3× Finals MVP" },
      { name: "Tim Duncan",            value: 15, hint: "5× NBA Champion · 3× Finals MVP" },
      { name: "John Havlicek",         value: 13, hint: "8× NBA Champion · 1974 Finals MVP" },
      { name: "Dwyane Wade",           value: 13, hint: "3× NBA Champion · 2006 Finals MVP" },
      { name: "Kevin Durant",          value: 14, hint: "2× NBA Champion · 2× Finals MVP" },
      { name: "Michael Jordan",        value: 14, hint: "6× NBA Champion · 6× Finals MVP" },
      { name: "Dirk Nowitzki",         value: 14, hint: "2011 NBA Champion · 2011 Finals MVP" },
      { name: "Magic Johnson",         value: 12, hint: "5× NBA Champion · 3× Finals MVP" },
      { name: "Larry Bird",            value: 12, hint: "3× NBA Champion · 3× MVP" },
      { name: "Isiah Thomas",          value: 12, hint: "2× NBA Champion · 1990 Finals MVP" },
      { name: "Chris Paul",            value: 12, hint: "4× assists title · 12× All-Star" },
      { name: "Charles Barkley",       value: 11, hint: "1993 MVP · Never won a ring" },
      { name: "Patrick Ewing",         value: 11, hint: "11× All-Star · Never won a ring" },
      { name: "Allen Iverson",         value: 11, hint: "2001 MVP · 2001 scoring title" },
      { name: "John Stockton",         value: 10, hint: "All-time assists & steals leader" },
      { name: "Stephen Curry",         value: 10, hint: "4× NBA Champion · 3-point record holder" },
      { name: "Carmelo Anthony",       value: 10, hint: "2003 draft class · Olympic gold medalist" },
      { name: "Russell Westbrook",     value:  9, hint: "2017 MVP · Triple-double season record" },
      { name: "Reggie Miller",         value:  5, hint: "Miller Time · Knicks rivalry icon" },
      { name: "Ray Allen",             value: 10, hint: "2013 Corner Three · 2× NBA Champion" },
    ],
  },
  {
    id: "threespm",
    label: "Career 3PM",
    description: "Total three-pointers made (career)",
    unit: "3PM",
    format: "integer",
    players: [
      { name: "Stephen Curry",         value: 3747, hint: "4× NBA Champion · All-time 3PM record" },
      { name: "James Harden",          value: 3100, hint: "2018 MVP · 10× All-Star" },
      { name: "Damian Lillard",        value: 2793, hint: "7× All-Star · 2024 Olympic gold" },
      { name: "Ray Allen",             value: 2973, hint: "Held all-time 3PM record until 2021" },
      { name: "Reggie Miller",         value: 2560, hint: "Held all-time 3PM record until 2011" },
      { name: "Kyle Korver",           value: 2450, hint: "5× All-Star · 43% career 3P% · 53.6% in 2009–10 (best ever)" },
      { name: "Klay Thompson",         value: 2487, hint: "4× NBA Champion · 60-pt game on 11 dribbles" },
      { name: "LeBron James",          value: 2340, hint: "4× NBA Champion · All-Time scoring leader" },
      { name: "Vince Carter",          value: 2290, hint: "22 seasons · 2000 Dunk Contest legend" },
      { name: "Jason Terry",           value: 2282, hint: "2011 NBA Champion · 'The Jet'" },
      { name: "Paul George",           value: 2250, hint: "9× All-Star · 2× Olympic gold" },
      { name: "Paul Pierce",           value: 1823, hint: "2008 NBA Champion · 2008 Finals MVP" },
      { name: "Dirk Nowitzki",         value: 1982, hint: "2011 NBA Champion · 2011 Finals MVP" },
      { name: "Jason Kidd",            value: 1988, hint: "2011 NBA Champion · 10× All-Star" },
      { name: "Kevin Durant",          value: 1900, hint: "2× NBA Champion · 2× Finals MVP" },
      { name: "Carmelo Anthony",       value: 1609, hint: "10× All-Star · 2003 draft class" },
      { name: "Michael Jordan",        value:  581, hint: "6× NBA Champion · 6× Finals MVP" },
      { name: "Charles Barkley",       value:  274, hint: "1993 MVP · Never won a ring" },
      { name: "Shaquille O'Neal",      value:    1, hint: "4× NBA Champion · Made exactly 1 career three" },
      { name: "Kareem Abdul-Jabbar",   value:    1, hint: "6× NBA Champion · Made exactly 1 career three" },
      { name: "Wilt Chamberlain",      value:    0, hint: "Retired before the 3-point line existed (1973)" },
    ],
  },
];
