export interface Player {
  id: string;
  name: string;
  team: string;
  position: string;
  jersey: string;
  teamColor: string;
  stats: {
    ppg: number;
    rpg: number;
    apg: number;
  };
  accolades: string[];
  era: string;
}

export interface Trio {
  id: string;
  category: string;
  description: string;
  players: [Player, Player, Player];
}

const PLAYERS: Record<string, Player> = {
  lebron: {
    id: "lebron",
    name: "LeBron James",
    team: "Los Angeles Lakers",
    position: "SF",
    jersey: "23",
    teamColor: "#552583",
    stats: { ppg: 27.1, rpg: 7.5, apg: 7.4 },
    accolades: ["4x Champion", "4x MVP", "21x All-Star"],
    era: "2003–present",
  },
  jordan: {
    id: "jordan",
    name: "Michael Jordan",
    team: "Chicago Bulls",
    position: "SG",
    jersey: "23",
    teamColor: "#CE1141",
    stats: { ppg: 30.1, rpg: 6.2, apg: 5.3 },
    accolades: ["6x Champion", "6x Finals MVP", "5x MVP"],
    era: "1984–2003",
  },
  kobe: {
    id: "kobe",
    name: "Kobe Bryant",
    team: "Los Angeles Lakers",
    position: "SG",
    jersey: "24",
    teamColor: "#552583",
    stats: { ppg: 25.0, rpg: 5.2, apg: 4.7 },
    accolades: ["5x Champion", "1x MVP", "18x All-Star"],
    era: "1996–2016",
  },
  curry: {
    id: "curry",
    name: "Stephen Curry",
    team: "Golden State Warriors",
    position: "PG",
    jersey: "30",
    teamColor: "#1D428A",
    stats: { ppg: 24.8, rpg: 4.6, apg: 6.4 },
    accolades: ["4x Champion", "2x MVP", "2x scoring title"],
    era: "2009–present",
  },
  durant: {
    id: "durant",
    name: "Kevin Durant",
    team: "Phoenix Suns",
    position: "SF",
    jersey: "35",
    teamColor: "#1D1160",
    stats: { ppg: 27.3, rpg: 7.0, apg: 4.4 },
    accolades: ["2x Champion", "2x Finals MVP", "1x MVP"],
    era: "2007–present",
  },
  harden: {
    id: "harden",
    name: "James Harden",
    team: "Los Angeles Clippers",
    position: "SG",
    jersey: "1",
    teamColor: "#C8102E",
    stats: { ppg: 25.0, rpg: 5.4, apg: 7.1 },
    accolades: ["1x MVP", "3x scoring title", "10x All-Star"],
    era: "2009–present",
  },
  shaq: {
    id: "shaq",
    name: "Shaquille O'Neal",
    team: "Los Angeles Lakers",
    position: "C",
    jersey: "34",
    teamColor: "#552583",
    stats: { ppg: 23.7, rpg: 10.9, apg: 2.5 },
    accolades: ["4x Champion", "3x Finals MVP", "1x MVP"],
    era: "1992–2011",
  },
  hakeem: {
    id: "hakeem",
    name: "Hakeem Olajuwon",
    team: "Houston Rockets",
    position: "C",
    jersey: "34",
    teamColor: "#CE1141",
    stats: { ppg: 21.8, rpg: 11.1, apg: 2.5 },
    accolades: ["2x Champion", "2x Finals MVP", "1x MVP"],
    era: "1984–2002",
  },
  ewing: {
    id: "ewing",
    name: "Patrick Ewing",
    team: "New York Knicks",
    position: "C",
    jersey: "33",
    teamColor: "#F58426",
    stats: { ppg: 21.0, rpg: 9.8, apg: 1.9 },
    accolades: ["11x All-Star", "1x Rookie of the Year", "HOF 2008"],
    era: "1985–2002",
  },
  jokic: {
    id: "jokic",
    name: "Nikola Jokic",
    team: "Denver Nuggets",
    position: "C",
    jersey: "15",
    teamColor: "#FEC524",
    stats: { ppg: 26.4, rpg: 12.4, apg: 9.0 },
    accolades: ["1x Champion", "3x MVP", "1x Finals MVP"],
    era: "2015–present",
  },
  embiid: {
    id: "embiid",
    name: "Joel Embiid",
    team: "Philadelphia 76ers",
    position: "C",
    jersey: "21",
    teamColor: "#006BB6",
    stats: { ppg: 27.3, rpg: 11.3, apg: 3.8 },
    accolades: ["1x MVP", "1x scoring title", "7x All-Star"],
    era: "2016–present",
  },
  giannis: {
    id: "giannis",
    name: "Giannis Antetokounmpo",
    team: "Milwaukee Bucks",
    position: "PF",
    jersey: "34",
    teamColor: "#00471B",
    stats: { ppg: 28.9, rpg: 11.6, apg: 5.8 },
    accolades: ["1x Champion", "2x MVP", "1x Finals MVP"],
    era: "2013–present",
  },
  kyrie: {
    id: "kyrie",
    name: "Kyrie Irving",
    team: "Dallas Mavericks",
    position: "PG",
    jersey: "2",
    teamColor: "#00538C",
    stats: { ppg: 23.6, rpg: 3.8, apg: 5.7 },
    accolades: ["1x Champion", "1x Rookie of the Year", "7x All-Star"],
    era: "2011–present",
  },
  dame: {
    id: "dame",
    name: "Damian Lillard",
    team: "Milwaukee Bucks",
    position: "PG",
    jersey: "0",
    teamColor: "#00471B",
    stats: { ppg: 24.7, rpg: 4.2, apg: 6.6 },
    accolades: ["1x scoring title", "7x All-Star", "1x Finals MVP"],
    era: "2012–present",
  },
  cp3: {
    id: "cp3",
    name: "Chris Paul",
    team: "San Antonio Spurs",
    position: "PG",
    jersey: "3",
    teamColor: "#C4CED4",
    stats: { ppg: 17.0, rpg: 4.5, apg: 9.4 },
    accolades: ["12x All-Star", "1x steals title", "HOF 2023"],
    era: "2005–present",
  },
  timD: {
    id: "timD",
    name: "Tim Duncan",
    team: "San Antonio Spurs",
    position: "PF",
    jersey: "21",
    teamColor: "#C4CED4",
    stats: { ppg: 19.0, rpg: 10.8, apg: 3.0 },
    accolades: ["5x Champion", "2x MVP", "3x Finals MVP"],
    era: "1997–2016",
  },
  dirk: {
    id: "dirk",
    name: "Dirk Nowitzki",
    team: "Dallas Mavericks",
    position: "PF",
    jersey: "41",
    teamColor: "#00538C",
    stats: { ppg: 20.7, rpg: 7.5, apg: 2.4 },
    accolades: ["1x Champion", "1x MVP", "1x Finals MVP"],
    era: "1998–2019",
  },
  kg: {
    id: "kg",
    name: "Kevin Garnett",
    team: "Minnesota Timberwolves",
    position: "PF",
    jersey: "21",
    teamColor: "#236192",
    stats: { ppg: 17.8, rpg: 10.0, apg: 3.7 },
    accolades: ["1x Champion", "1x MVP", "15x All-Star"],
    era: "1995–2016",
  },
  kareem: {
    id: "kareem",
    name: "Kareem Abdul-Jabbar",
    team: "Los Angeles Lakers",
    position: "C",
    jersey: "33",
    teamColor: "#552583",
    stats: { ppg: 24.6, rpg: 11.2, apg: 3.6 },
    accolades: ["6x Champion", "6x MVP", "19x All-Star"],
    era: "1969–1989",
  },
  wilt: {
    id: "wilt",
    name: "Wilt Chamberlain",
    team: "Los Angeles Lakers",
    position: "C",
    jersey: "13",
    teamColor: "#552583",
    stats: { ppg: 30.1, rpg: 22.9, apg: 4.4 },
    accolades: ["2x Champion", "4x MVP", "13x All-Star"],
    era: "1959–1973",
  },
  russell: {
    id: "russell",
    name: "Bill Russell",
    team: "Boston Celtics",
    position: "C",
    jersey: "6",
    teamColor: "#007A33",
    stats: { ppg: 15.1, rpg: 22.5, apg: 4.3 },
    accolades: ["11x Champion", "5x MVP", "12x All-Star"],
    era: "1956–1969",
  },
  dwyane: {
    id: "dwyane",
    name: "Dwyane Wade",
    team: "Miami Heat",
    position: "SG",
    jersey: "3",
    teamColor: "#98002E",
    stats: { ppg: 22.0, rpg: 4.7, apg: 5.4 },
    accolades: ["3x Champion", "1x Finals MVP", "13x All-Star"],
    era: "2003–2019",
  },
  tmac: {
    id: "tmac",
    name: "Tracy McGrady",
    team: "Houston Rockets",
    position: "SG",
    jersey: "1",
    teamColor: "#CE1141",
    stats: { ppg: 19.6, rpg: 5.6, apg: 4.4 },
    accolades: ["2x scoring title", "7x All-Star", "HOF 2017"],
    era: "1997–2012",
  },
  vince: {
    id: "vince",
    name: "Vince Carter",
    team: "Toronto Raptors",
    position: "SG",
    jersey: "15",
    teamColor: "#CE1141",
    stats: { ppg: 16.7, rpg: 4.3, apg: 3.1 },
    accolades: ["8x All-Star", "1x Rookie of the Year", "HOF 2024"],
    era: "1998–2020",
  },
  magic: {
    id: "magic",
    name: "Magic Johnson",
    team: "Los Angeles Lakers",
    position: "PG",
    jersey: "32",
    teamColor: "#552583",
    stats: { ppg: 19.5, rpg: 7.2, apg: 11.2 },
    accolades: ["5x Champion", "3x MVP", "3x Finals MVP"],
    era: "1979–1996",
  },
  bird: {
    id: "bird",
    name: "Larry Bird",
    team: "Boston Celtics",
    position: "SF",
    jersey: "33",
    teamColor: "#007A33",
    stats: { ppg: 24.3, rpg: 10.0, apg: 6.3 },
    accolades: ["3x Champion", "3x MVP", "3x Finals MVP"],
    era: "1979–1992",
  },
  isiah: {
    id: "isiah",
    name: "Isiah Thomas",
    team: "Detroit Pistons",
    position: "PG",
    jersey: "11",
    teamColor: "#C8102E",
    stats: { ppg: 19.2, rpg: 3.6, apg: 9.3 },
    accolades: ["2x Champion", "2x Finals MVP", "12x All-Star"],
    era: "1981–1994",
  },
  tatum: {
    id: "tatum",
    name: "Jayson Tatum",
    team: "Boston Celtics",
    position: "SF",
    jersey: "0",
    teamColor: "#007A33",
    stats: { ppg: 26.9, rpg: 8.1, apg: 4.9 },
    accolades: ["1x Champion", "1x Finals MVP", "6x All-Star"],
    era: "2017–present",
  },
  luka: {
    id: "luka",
    name: "Luka Doncic",
    team: "Los Angeles Lakers",
    position: "PG",
    jersey: "77",
    teamColor: "#552583",
    stats: { ppg: 28.7, rpg: 8.7, apg: 8.3 },
    accolades: ["1x MVP", "1x Rookie of the Year", "5x All-Star"],
    era: "2018–present",
  },
  booker: {
    id: "booker",
    name: "Devin Booker",
    team: "Phoenix Suns",
    position: "SG",
    jersey: "1",
    teamColor: "#1D1160",
    stats: { ppg: 22.9, rpg: 4.5, apg: 4.8 },
    accolades: ["1x scoring title", "3x All-Star", "1x Olympic gold"],
    era: "2015–present",
  },
};

export const TRIOS: Trio[] = [
  {
    id: "goats",
    category: "The GOAT Debate",
    description: "The eternal argument: who's the greatest of all time?",
    players: [PLAYERS.lebron, PLAYERS.jordan, PLAYERS.kobe],
  },
  {
    id: "modern-scorers",
    category: "Modern Scoring Icons",
    description: "Three of the most prolific scorers of the current era",
    players: [PLAYERS.curry, PLAYERS.durant, PLAYERS.harden],
  },
  {
    id: "90s-centers",
    category: "90s Dominant Big Men",
    description: "The era when centers ruled the paint",
    players: [PLAYERS.shaq, PLAYERS.hakeem, PLAYERS.ewing],
  },
  {
    id: "modern-mvps",
    category: "Modern MVP Club",
    description: "Today's best players battling for hardware",
    players: [PLAYERS.jokic, PLAYERS.embiid, PLAYERS.giannis],
  },
  {
    id: "elite-pgs",
    category: "Elite Point Guards",
    description: "Who runs the floor better?",
    players: [PLAYERS.kyrie, PLAYERS.dame, PLAYERS.cp3],
  },
  {
    id: "pf-legends",
    category: "Power Forward Legends",
    description: "The three best power forwards of all time",
    players: [PLAYERS.timD, PLAYERS.dirk, PLAYERS.kg],
  },
  {
    id: "all-time-centers",
    category: "All-Time Centers",
    description: "The most dominant big men in NBA history",
    players: [PLAYERS.kareem, PLAYERS.wilt, PLAYERS.russell],
  },
  {
    id: "athletic-sgs",
    category: "Athletic Shooting Guards",
    description: "Explosive guards who thrilled the crowd",
    players: [PLAYERS.dwyane, PLAYERS.tmac, PLAYERS.vince],
  },
  {
    id: "80s-legends",
    category: "80s Legends",
    description: "The players who built the modern NBA",
    players: [PLAYERS.magic, PLAYERS.bird, PLAYERS.isiah],
  },
  {
    id: "young-stars",
    category: "Young Superstars",
    description: "The faces of today's NBA",
    players: [PLAYERS.tatum, PLAYERS.luka, PLAYERS.booker],
  },
];

export function getRandomTrio(): Trio {
  return TRIOS[Math.floor(Math.random() * TRIOS.length)];
}

export function getTrioById(id: string): Trio | undefined {
  return TRIOS.find((t) => t.id === id);
}
